In [2]:
import pandas as pd
import datacompy

print(pd.__version__)
print(datacompy.__version__)

3.0.6
1.0.4

In [3]:
#create datasets
import pandas as pd

df_old = pd.DataFrame({
    "customer_id": [101, 102, 103],
    "name": ["Alice", "Bob", "Charlie"],
    "amount": [100, 200, 300]
})

df_new = pd.DataFrame({
    "customer_id": [101, 102, 103],
    "name": ["Alice", "Bob", "Charlie"],
    "amount": [100, 250, 300]
})

In [5]:
#first comparison
import datacompy

compare = datacompy.PandasCompare(
    df_old,
    df_new,
    join_columns=["customer_id"]
)

In [7]:
print(compare.report())

DataComPy Comparison
-------------------

DataFrame Summary
-----------------

DataFrame  Columns  Rows
------------------------
df1               3     3
df2               3     3


Column Summary
--------------

Number of columns in common: 3
Number of columns in df1 but not in df2: 0
Number of columns in df2 but not in df1: 0

Row Summary
-----------

Matched on: customer_id
Any duplicates on match values: No
Default Absolute Tolerance: 0
Default Relative Tolerance: 0
Number of rows in common: 3
Number of rows in df1 but not in df2: 0
Number of rows in df2 but not in df1: 0

Number of rows with some compared columns unequal: 1
Number of rows with all compared columns equal: 2

Column Comparison
-----------------

Number of columns compared with some values unequal: 1
Number of columns compared with all values equal: 2
Total number of values which compare unequal: 1

Columns with Unequal Values or Types
------------------------------------

Column               df1 dtype       df2 dtype        # Unequal   Max Diff  # Null Diff    Rel Tol    Abs Tol
-------------------- --------------- --------------- ---------- ---------- ------------ ---------- ----------
amount               int64           int64                    1    50.0000            0     0.0000     0.0000


Sample Rows with Unequal Values
-------------------------------

   customer_id  amount (df1)  amount (df2)
0          102           200           250

In [8]:
df_new = pd.DataFrame({
    "customer_id": [101, 102, 103, 104],
    "name": ["Alice", "Bob", "Charlie", "David"],
    "amount": [100, 250, 300, 400]
})

In [9]:
df_new

   customer_id     name  amount
0          101    Alice     100
1          102      Bob     250
2          103  Charlie     300
3          104    David     400

In [10]:
df_old

   customer_id     name  amount
0          101    Alice     100
1          102      Bob     200
2          103  Charlie     300

In [11]:
report2 = datacompy.PandasCompare(
df1 = df_old, 
df2 = df_new, 
join_columns='customer_id'

)

In [12]:
print(report2.report())

DataComPy Comparison
-------------------

DataFrame Summary
-----------------

DataFrame  Columns  Rows
------------------------
df1               3     3
df2               3     4


Column Summary
--------------

Number of columns in common: 3
Number of columns in df1 but not in df2: 0
Number of columns in df2 but not in df1: 0

Row Summary
-----------

Matched on: customer_id
Any duplicates on match values: No
Default Absolute Tolerance: 0
Default Relative Tolerance: 0
Number of rows in common: 3
Number of rows in df1 but not in df2: 0
Number of rows in df2 but not in df1: 1

Number of rows with some compared columns unequal: 1
Number of rows with all compared columns equal: 2

Column Comparison
-----------------

Number of columns compared with some values unequal: 1
Number of columns compared with all values equal: 2
Total number of values which compare unequal: 1

Columns with Unequal Values or Types
------------------------------------

Column               df1 dtype       df2 dtype        # Unequal   Max Diff  # Null Diff    Rel Tol    Abs Tol
-------------------- --------------- --------------- ---------- ---------- ------------ ---------- ----------
amount               int64           int64                    1    50.0000            0     0.0000     0.0000


Sample Rows with Unequal Values
-------------------------------

   customer_id  amount (df1)  amount (df2)
0          102         200.0           250




Sample Rows Only in df2 (First 10 Columns)
------------------------------------------

   customer_id   name  amount
0          104  David     400

In [13]:
#using composite key 
orders_old = pd.DataFrame({
    "customer_id": [101, 101, 102],
    "order_id": [5001, 5002, 5003],
    "product": ["Laptop", "Mouse", "Keyboard"],
    "amount": [1000, 50, 80]
})

orders_new = pd.DataFrame({
    "customer_id": [101, 101, 102],
    "order_id": [5001, 5002, 5003],
    "product": ["Laptop", "Mouse", "Keyboard"],
    "amount": [1050, 50, 80]
})

In [15]:
composite_key_results1 = datacompy.PandasCompare(
    orders_old,
    orders_new,
    join_columns=["customer_id"]
)

In [18]:
print(composite_key_results1.report())

DataComPy Comparison
-------------------

DataFrame Summary
-----------------

DataFrame  Columns  Rows
------------------------
df1               4     3
df2               4     3


Column Summary
--------------

Number of columns in common: 4
Number of columns in df1 but not in df2: 0
Number of columns in df2 but not in df1: 0

Row Summary
-----------

Matched on: customer_id
Any duplicates on match values: Yes
Default Absolute Tolerance: 0
Default Relative Tolerance: 0
Number of rows in common: 3
Number of rows in df1 but not in df2: 0
Number of rows in df2 but not in df1: 0

Number of rows with some compared columns unequal: 1
Number of rows with all compared columns equal: 2

Column Comparison
-----------------

Number of columns compared with some values unequal: 1
Number of columns compared with all values equal: 3
Total number of values which compare unequal: 1

Columns with Unequal Values or Types
------------------------------------

Column               df1 dtype       df2 dtype        # Unequal   Max Diff  # Null Diff    Rel Tol    Abs Tol
-------------------- --------------- --------------- ---------- ---------- ------------ ---------- ----------
amount               int64           int64                    1    50.0000            0     0.0000     0.0000


Sample Rows with Unequal Values
-------------------------------

   customer_id  amount (df1)  amount (df2)
0          101          1000          1050

In [20]:
composite_key_results2 = datacompy.PandasCompare(
    orders_old,
    orders_new,
    join_columns=["customer_id","order_id"]
)
print(composite_key_results2.report())

DataComPy Comparison
-------------------

DataFrame Summary
-----------------

DataFrame  Columns  Rows
------------------------
df1               4     3
df2               4     3


Column Summary
--------------

Number of columns in common: 4
Number of columns in df1 but not in df2: 0
Number of columns in df2 but not in df1: 0

Row Summary
-----------

Matched on: customer_id, order_id
Any duplicates on match values: No
Default Absolute Tolerance: 0
Default Relative Tolerance: 0
Number of rows in common: 3
Number of rows in df1 but not in df2: 0
Number of rows in df2 but not in df1: 0

Number of rows with some compared columns unequal: 1
Number of rows with all compared columns equal: 2

Column Comparison
-----------------

Number of columns compared with some values unequal: 1
Number of columns compared with all values equal: 3
Total number of values which compare unequal: 1

Columns with Unequal Values or Types
------------------------------------

Column               df1 dtype       df2 dtype        # Unequal   Max Diff  # Null Diff    Rel Tol    Abs Tol
-------------------- --------------- --------------- ---------- ---------- ------------ ---------- ----------
amount               int64           int64                    1    50.0000            0     0.0000     0.0000


Sample Rows with Unequal Values
-------------------------------

   customer_id  order_id  amount (df1)  amount (df2)
0          101      5001          1000          1050

In [21]:
#setting up tolerances 
sales_old = pd.DataFrame({
    "product_id": [1, 2, 3],
    "price": [100.00, 200.00, 300.00]
})

sales_new = pd.DataFrame({
    "product_id": [1, 2, 3],
    "price": [100.01, 200.03, 300.10]
})

In [23]:
#this will show unequal values due to tolerance not set

compare = datacompy.PandasCompare(
    sales_old,
    sales_new,
    join_columns=["product_id"]
)

print(compare.report())

DataComPy Comparison
-------------------

DataFrame Summary
-----------------

DataFrame  Columns  Rows
------------------------
df1               2     3
df2               2     3


Column Summary
--------------

Number of columns in common: 2
Number of columns in df1 but not in df2: 0
Number of columns in df2 but not in df1: 0

Row Summary
-----------

Matched on: product_id
Any duplicates on match values: No
Default Absolute Tolerance: 0
Default Relative Tolerance: 0
Number of rows in common: 3
Number of rows in df1 but not in df2: 0
Number of rows in df2 but not in df1: 0

Number of rows with some compared columns unequal: 3
Number of rows with all compared columns equal: 0

Column Comparison
-----------------

Number of columns compared with some values unequal: 1
Number of columns compared with all values equal: 1
Total number of values which compare unequal: 3

Columns with Unequal Values or Types
------------------------------------

Column               df1 dtype       df2 dtype        # Unequal   Max Diff  # Null Diff    Rel Tol    Abs Tol
-------------------- --------------- --------------- ---------- ---------- ------------ ---------- ----------
price                float64         float64                  3     0.1000            0     0.0000     0.0000


Sample Rows with Unequal Values
-------------------------------

   product_id  price (df1)  price (df2)
0           3        300.0       300.10
1           1        100.0       100.01
2           2        200.0       200.03

In [26]:
compare = datacompy.PandasCompare(
    sales_old,
    sales_new,
    join_columns=["product_id"],
    abs_tol=0.05, #actual difference
    rel_tol=0.001 # for the number how much is the differences(relative tolernace)
)

print(compare.report())

DataComPy Comparison
-------------------

DataFrame Summary
-----------------

DataFrame  Columns  Rows
------------------------
df1               2     3
df2               2     3


Column Summary
--------------

Number of columns in common: 2
Number of columns in df1 but not in df2: 0
Number of columns in df2 but not in df1: 0

Row Summary
-----------

Matched on: product_id
Any duplicates on match values: No
Default Absolute Tolerance: 0.05
Default Relative Tolerance: 0.001
Number of rows in common: 3
Number of rows in df1 but not in df2: 0
Number of rows in df2 but not in df1: 0

Number of rows with some compared columns unequal: 0
Number of rows with all compared columns equal: 3

Column Comparison
-----------------

Number of columns compared with some values unequal: 0
Number of columns compared with all values equal: 2
Total number of values which compare unequal: 0

Column Differences

In [ ]:
df1 = pd.DataFrame({
    "customer_id": [101, 102, 103],
    "name": ["Alice", "Bob", "Charlie"],
    "amount": [100, 200, 300]
})

df2 = pd.DataFrame({
    "customer_id": [101, 102, 103],
    "name": ["Alice", "Bob", "Charlie"],
    "amount": [100, 200, 400],
    "email": [
        "alice@example.com",
        "bob@example.com",
        "charlie@example.com"
    ]
})

In [31]:
compare = datacompy.PandasCompare(
    df1,
    df2,
    join_columns=["customer_id"],
    
)

print(compare.report())

DataComPy Comparison
-------------------

DataFrame Summary
-----------------

DataFrame  Columns  Rows
------------------------
df1               3     3
df2               4     3


Column Summary
--------------

Number of columns in common: 3
Number of columns in df1 but not in df2: 0
Number of columns in df2 but not in df1: 1 ['email']

Row Summary
-----------

Matched on: customer_id
Any duplicates on match values: No
Default Absolute Tolerance: 0
Default Relative Tolerance: 0
Number of rows in common: 3
Number of rows in df1 but not in df2: 0
Number of rows in df2 but not in df1: 0

Number of rows with some compared columns unequal: 0
Number of rows with all compared columns equal: 3

Column Comparison
-----------------

Number of columns compared with some values unequal: 0
Number of columns compared with all values equal: 3
Total number of values which compare unequal: 0

In [34]:
print(f"matches(ignore_extra_columns=True): {compare.matches(ignore_extra_columns=True)}")
print(f"all_columns_match(): {compare.all_columns_match()}")
print(f"all_rows_overlap(): {compare.all_rows_overlap()}")
print(f"intersect_rows_match(): {compare.intersect_rows_match()}")

matches(ignore_extra_columns=True): True
all_columns_match(): False
all_rows_overlap(): True
intersect_rows_match(): True

In [36]:
#Find columns unique to each DataFrame
print(compare.df1_unq_columns())
print(compare.df2_unq_columns())

OrderedSet()
OrderedSet(['email'])

In [37]:
print(compare.all_mismatch())

Empty DataFrame
Columns: [customer_id, name_df1, name_df2, amount_df1, amount_df2]
Index: []

In [39]:
#sample mismatch 
print(compare.sample_mismatch('amount'))

Empty DataFrame
Columns: [customer_id, amount_df1, amount_df2]
Index: []