In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(r'data\customers.csv')

In [3]:
df

  customer_id           name                email  age country    status
0        C001  Alice Johnson    alice@example.com   32   India    active
1        C002      Bob Smith      bob@example.com   45   India    active
2        C003  Charlie Brown  charlie@example.com   28     USA    active
3        C004   Diana Prince    diana@example.com   35      UK  inactive
4        C005     Ethan Hunt    ethan@example.com   41     USA    active
5        C006    Fiona Green    fiona@example.com   29   India    active
6        C007  George Miller   george@example.com   52  Canada    active
7        C008     Hannah Lee   hannah@example.com   24   India    active
8        C009     Ian Wright      ian@example.com   38      UK    active
9        C010    Julia Adams    julia@example.com   31     USA  inactive

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   customer_id  10 non-null     str
 1   name         10 non-null     str
 2   email        10 non-null     str
 3   age          10 non-null     int64
 4   country      10 non-null     str
 5   status       10 non-null     str
dtypes: int64(1), str(5)
memory usage: 612.0 bytes

In [5]:
#How many rows and columns does the dataset have?
print(df.shape) # 10 rows and 6 columns 

#Should customer_id be nullable? 
# no 
print(df.dtypes)

#Should customer_id be unique?
#yes 
print(df.isnull().sum())

#What values should status be allowed to contain?
#active and inactive 
print(df["customer_id"].nunique())

#What would be a reasonable validation rule for age?
#age should be between 10 and 100

(10, 6)
customer_id      str
name             str
email            str
age            int64
country          str
status           str
dtype: object
customer_id    0
name           0
email          0
age            0
country        0
status         0
dtype: int64
10

In [6]:
print(df["country"].value_counts())
print(df["status"].value_counts())

country
India     4
USA       3
UK        2
Canada    1
Name: count, dtype: int64
status
active      8
inactive    2
Name: count, dtype: int64

### An Expectation

An **Expectation** is essentially a statement about what you expect your data to look like.

For example:

> `customer_id` should never be null.

or:

> `age` should be between 18 and 100.

or:

> `status` should only contain `active` or `inactive`.

In [7]:
#setting up expectations
import great_expectations as gx

In [8]:
context = gx.get_context()

The idea is directionally right, but I'd refine it to:

> **The Data Context is the main entry point for managing GX configuration and metadata, including data sources, assets, expectation suites, validation workflows, and results.**

The actual **validation** is what evaluates Expectations against a Batch of data.

### Think of the responsibilities like this

**Data Context**

> "What does my GX project know about?"

**Data Source**

> "Where does my data come from?"

**Data Asset**

> "Which logical dataset am I validating?"

**Batch**

> "Which particular data am I validating right now?"

**Expectation**

> "What should be true about this data?"

**Validation**

> "Does this particular Batch satisfy those expectations?"

### Project 1 — GX Validation Flow

So eventually our Project 1 will look roughly like this:

```text
customers.csv
     ↓
Data Source
     ↓
Customer Data Asset
     ↓
Customer Batch
     ↓
Customer Expectations
     ├── customer_id not null
     ├── customer_id unique
     ├── age between 18 and 100
     ├── status in {active, inactive}
     └── email not null
     ↓
Validation
     ↓
Validation Results
     ↓
PASS / FAIL

In [9]:
print(type(context))

<class 'great_expectations.data_context.data_context.file_data_context.FileDataContext'>

EphemeralDataContext -> GX created the context temporarily in memory rather than loading a persistent GX project configuration from disk.

In [10]:
print(dir(context.data_sources))

['_DataSourceManager__crud_registry', '__annotations__', '__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__firstlineno__', '__format__', '__ge__', '__getattr__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__static_attributes__', '__str__', '__subclasshook__', '__weakref__', '_bind_asset_factory_method_if_not_present', '_build_add_asset_docstring', '_data_context', '_datasource_passed_in', '_datasource_passed_in_as_only_argument', '_register_add_datasource', '_register_add_or_update_datasource', '_register_assets', '_register_crud_method', '_register_datasource', '_register_delete_datasource', '_register_update_datasource', '_validate_current_datasource_type', 'add_alloy', 'add_aurora', 'add_bigquery', 'add_citus', 'add_databricks_sql', 'add_fabric', 'add_fabric_powerbi', 'add_neon', 'add_or_update_alloy', 'add_or_update_aurora', 'add_or_update_bigquery', 'add_or_update_citus', 'add_or_update_databricks_sql', 'add_or_update_fabric', 'add_or_update_fabric_powerbi', 'add_or_update_neon', 'add_or_update_pandas', 'add_or_update_pandas_abs', 'add_or_update_pandas_dbfs', 'add_or_update_pandas_filesystem', 'add_or_update_pandas_gcs', 'add_or_update_pandas_s3', 'add_or_update_postgres', 'add_or_update_redshift', 'add_or_update_snowflake', 'add_or_update_spark', 'add_or_update_spark_abs', 'add_or_update_spark_dbfs', 'add_or_update_spark_filesystem', 'add_or_update_spark_gcs', 'add_or_update_spark_s3', 'add_or_update_sql', 'add_or_update_sql_server', 'add_or_update_sqlite', 'add_pandas', 'add_pandas_abs', 'add_pandas_dbfs', 'add_pandas_filesystem', 'add_pandas_gcs', 'add_pandas_s3', 'add_postgres', 'add_redshift', 'add_snowflake', 'add_spark', 'add_spark_abs', 'add_spark_dbfs', 'add_spark_filesystem', 'add_spark_gcs', 'add_spark_s3', 'add_sql', 'add_sql_server', 'add_sqlite', 'all', 'create_add_crud_method', 'create_add_or_update_crud_method', 'create_delete_crud_method', 'create_update_crud_method', 'delete', 'delete_alloy', 'delete_aurora', 'delete_bigquery', 'delete_citus', 'delete_databricks_sql', 'delete_fabric', 'delete_fabric_powerbi', 'delete_neon', 'delete_pandas', 'delete_pandas_abs', 'delete_pandas_dbfs', 'delete_pandas_filesystem', 'delete_pandas_gcs', 'delete_pandas_s3', 'delete_postgres', 'delete_redshift', 'delete_snowflake', 'delete_spark', 'delete_spark_abs', 'delete_spark_dbfs', 'delete_spark_filesystem', 'delete_spark_gcs', 'delete_spark_s3', 'delete_sql', 'delete_sql_server', 'delete_sqlite', 'factories', 'get', 'pandas_default', 'register_datasource', 'type_lookup', 'update_alloy', 'update_aurora', 'update_bigquery', 'update_citus', 'update_databricks_sql', 'update_fabric', 'update_fabric_powerbi', 'update_neon', 'update_pandas', 'update_pandas_abs', 'update_pandas_dbfs', 'update_pandas_filesystem', 'update_pandas_gcs', 'update_pandas_s3', 'update_postgres', 'update_redshift', 'update_snowflake', 'update_spark', 'update_spark_abs', 'update_spark_dbfs', 'update_spark_filesystem', 'update_spark_gcs', 'update_spark_s3', 'update_sql', 'update_sql_server', 'update_sqlite']

In [11]:
data_source = context.data_sources.add_pandas(name='customer_data_source')
print(data_source)

id: 7059582c-3bbc-49e3-9147-52d997a0ddc0
name: customer_data_source
type: pandas

### Why doesn't GX just take `df`?

This is a useful conceptual distinction.

The **Data Source** represents *where/how data is accessed*.

The actual DataFrame is the **data itself**.

For example, a Pandas Data Source says:

> "I'm going to work with data that GX accesses through pandas."

It doesn't yet say:

> "Validate this particular DataFrame."

That's what the next layers — **Data Asset, Batch Definition, and Batch** — will establish.

In [12]:

data_asset = data_source.add_dataframe_asset(name='customer')

In [13]:
print(data_asset)

batch_metadata: {}
id: fcae5632-0af7-43f8-9346-e887c8c64069
name: customer
type: dataframe

## The Next Concept: Batch Definition

We're now at an important question:

> **Which actual data should GX validate?**

A **Data Asset** tells GX:

> "This represents customer data."

But it doesn't yet identify the particular data we want to validate.

That's where the **Batch Definition** comes in.

Think about it this way:

```text
Data Source
    │
    │  "How do I access data?"
    ↓
Data Asset
    │
    │  "What logical dataset is this?"
    ↓
Batch Definition
    │
    │  "How do I identify/retrieve a particular batch?"
    ↓
Batch
    │
    │  "Here is the actual data"
    ↓
Validation

In [14]:
print(dir(data_asset))

['Config', '_EXCLUDE_FROM_READER_OPTIONS', '__abstractmethods__', '__annotations__', '__class__', '__class_getitem__', '__class_vars__', '__concrete__', '__concrete_name__', '__config__', '__custom_root_type__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__exclude_fields__', '__fields__', '__fields_set__', '__firstlineno__', '__format__', '__ge__', '__get_validators__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__include_fields__', '__init__', '__init_subclass__', '__iter__', '__json_encoder__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__orig_bases__', '__parameterized_bases__', '__parameters__', '__post_root_validators__', '__pre_root_validators__', '__pretty__', '__private_attributes__', '__reduce__', '__reduce_ex__', '__repr__', '__repr_args__', '__repr_name__', '__repr_str__', '__rich_repr__', '__schema_cache__', '__setattr__', '__setstate__', '__signature__', '__sizeof__', '__slots__', '__static_attributes__', '__str__', '__subclasshook__', '__try_update_forward_refs__', '__validators__', '_abc_impl', '_batch_parameters_are_valid', '_calculate_keys', '_copy_and_set_values', '_data_connector', '_datasource', '_decompose_class', '_delete_batch_definition', '_enforce_dict_if_root', '_get_batch_metadata_from_batch_request', '_get_reader_method', '_get_reader_options_include', '_get_value', '_include_exclude_to_dict', '_init_private_attributes', '_iter', '_json_dict', '_order_by_validator', '_sort_batch_data_list', '_test_connection_error_message', '_validate_batch_request', 'add_batch_definition', 'add_batch_definition_whole_dataframe', 'batch_definitions', 'batch_metadata', 'build_batch_request', 'construct', 'copy', 'datasource', 'delete_batch_definition', 'dict', 'ensure_batch_metadata_is_not_none', 'from_orm', 'get_batch', 'get_batch_definition', 'get_batch_identifiers_list', 'get_batch_parameters_keys', 'id', 'json', 'name', 'order_by', 'parse_file', 'parse_obj', 'parse_raw', 'parse_yaml', 'schema', 'schema_json', 'sort_batch_identifiers_list', 'sort_batches', 'sort_legacy_batch_definitions', 'test_connection', 'type', 'update_batch_definition_field_set', 'update_forward_refs', 'validate', 'yaml']

For our current Project 1, add_batch_definition_whole_dataframe is the better choice.

In [15]:
batch_definition  = data_asset.add_batch_definition_whole_dataframe(name='customers_batch')

In [16]:
print(batch_definition)

id=UUID('2bb5286c-2727-4a2d-99e6-6d7bb0c8ef7c') name='customers_batch' partitioner=None

In [17]:
print(dir(batch_definition))

['Config', '__abstractmethods__', '__annotations__', '__class__', '__class_getitem__', '__class_vars__', '__concrete__', '__concrete_name__', '__config__', '__custom_root_type__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__exclude_fields__', '__fields__', '__fields_set__', '__firstlineno__', '__format__', '__ge__', '__get_validators__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__include_fields__', '__init__', '__init_subclass__', '__iter__', '__json_encoder__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__orig_bases__', '__parameterized_bases__', '__parameters__', '__post_root_validators__', '__pre_root_validators__', '__pretty__', '__private_attributes__', '__reduce__', '__reduce_ex__', '__repr__', '__repr_args__', '__repr_name__', '__repr_str__', '__rich_repr__', '__schema_cache__', '__setattr__', '__setstate__', '__signature__', '__sizeof__', '__slots__', '__static_attributes__', '__str__', '__subclasshook__', '__try_update_forward_refs__', '__validators__', '_abc_impl', '_calculate_keys', '_copy_and_set_values', '_data_asset', '_decompose_class', '_enforce_dict_if_root', '_get_value', '_init_private_attributes', '_is_added', '_is_fresh', '_iter', 'build_batch_request', 'construct', 'copy', 'data_asset', 'dict', 'from_orm', 'get_batch', 'get_batch_identifiers_list', 'id', 'identifier_bundle', 'is_fresh', 'json', 'name', 'parse_file', 'parse_obj', 'parse_raw', 'partitioner', 'save', 'schema', 'schema_json', 'set_data_asset', 'update_forward_refs', 'validate']

In [18]:
help(batch_definition.get_batch)

Help on method get_batch in module great_expectations.core.batch_definition:

get_batch(batch_parameters: 'Optional[BatchParameters]' = None) -> 'Batch' method of great_expectations.core.batch_definition.BatchDefinition instance
    --Public API--
    Retrieves a batch from the underlying asset. Defaults to the last batch
    from the asset's batch list.

    Args:
        batch_parameters: Additional parameters to be used in fetching the batch.
            Numeric batch parameters (e.g. year, month, day) take integer values;
            digit-string values are still accepted but are deprecated and emit a
            warning, with support for them removed in 2.0.

    Returns:
        A Batch of data.

In [19]:
batch = batch_definition.get_batch(    batch_parameters={
        "dataframe": df
    })

In [20]:
print(batch)

<great_expectations.datasource.fluent.interfaces.Batch object at 0x00000149AB09D550>

In [21]:
print(type(batch))

<class 'great_expectations.datasource.fluent.interfaces.Batch'>

In [22]:
print(dir(batch))

['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__firstlineno__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__static_attributes__', '__str__', '__subclasshook__', '__weakref__', '_batch_definition', '_batch_markers', '_batch_request', '_batch_spec', '_create_id', '_create_validator', '_data', '_data_asset', '_datasource', '_get_metrics_calculator', '_id', '_parse_metric_value', '_validate_expectation', '_validate_expectation_suite', 'batch_definition', 'batch_markers', 'batch_request', 'batch_spec', 'columns', 'compute_metrics', 'data', 'data_asset', 'datasource', 'head', 'id', 'metadata', 'validate']

In [23]:
print(help(batch))

Help on Batch in module great_expectations.datasource.fluent.interfaces object:

class Batch(builtins.object)
 |  Batch(
 |      datasource: 'Datasource',
 |      data_asset: 'DataAsset',
 |      batch_request: 'BatchRequest',
 |      data: 'BatchData',
 |      batch_markers: 'BatchMarkers',
 |      batch_spec: 'BatchSpec',
 |      batch_definition: 'LegacyBatchDefinition',
 |      metadata: 'Dict[str, Any] | None' = None
 |  )
 |
 |  --Public API--This represents a batch of data.
 |
 |  This is usually not the data itself but a hook to the data on an external datastore such as
 |  a spark or a sql database. An exception exists for pandas or any in-memory datastore.
 |
 |  Methods defined here:
 |
 |  __init__(
 |      self,
 |      datasource: 'Datasource',
 |      data_asset: 'DataAsset',
 |      batch_request: 'BatchRequest',
 |      data: 'BatchData',
 |      batch_markers: 'BatchMarkers',
 |      batch_spec: 'BatchSpec',
 |      batch_definition: 'LegacyBatchDefinition',
 |      metadata: 'Dict[str, Any] | None' = None
 |  )
 |      Initialize self.  See help(type(self)) for accurate signature.
 |
 |  columns(self) -> 'List[str]'
 |      --Public API--Return column names of this Batch.
 |
 |      Returns:
 |          list of column names.
 |
 |  compute_metrics(self, metrics: 'Metric[_MetricResultT] | list[Metric]') -> '_MetricResultT | MetricErrorResult | list[MetricResult]'
 |      Compute one or more metrics on this Batch.
 |
 |      Args:
 |          metrics: A single Metric or list of Metrics to compute.
 |                   Each Metric must be an instance of a concrete Metric subclass.
 |
 |      Returns:
 |          If a single Metric is provided, returns a single MetricResult.
 |          If a list of Metrics is provided, returns a list of MetricResults,
 |          in the same order as the input metrics were received.
 |          For metrics without a defined MetricResult generic type,
 |          the base MetricResult class will be returned.
 |          For metrics that raise an exception, a MetricErrorResult will be returned.
 |
 |      Examples:
 |          >>> batch.compute_metrics(BatchRowCount())
 |          BatchRowCountResult(id=..., value=1000)
 |
 |          >>> batch.compute_metrics([
 |          ...     BatchRowCount(),
 |          ...     ColumnMax(column="age")
 |          ... ])
 |          [BatchRowCountResult(id=..., value=1000), ColumnMaxResult(id=..., value=85)]
 |
 |      Notes:
 |          Until this mypy bug is resolved, lists of Metrics are being incorrectly
 |          inferred by the static type checker as list[Domain]. You can work around
 |          this by adding an explicit annotation (e.g. metrics: list[Metric] = ...)
 |          https://github.com/python/mypy/issues/18712
 |
 |  head(self, n_rows: 'StrictInt' = 5, fetch_all: 'StrictBool' = False) -> 'HeadData'
 |      --Public API--Return the first n rows of this Batch.
 |
 |      This method returns the first n rows for the Batch based on position.
 |
 |      For negative values of n_rows, this method returns all rows except the last n rows.
 |
 |      If n_rows is larger than the number of rows, this method returns all rows.
 |
 |      Args:
 |          n_rows: The number of rows to return from the Batch.
 |          fetch_all: If True, ignore n_rows and return the entire Batch.
 |
 |      Returns:
 |          HeadData
 |
 |  validate(
 |      self,
 |      expect: 'Expectation | ExpectationSuite',
 |      *,
 |      result_format: 'ResultFormatUnion' = <ResultFormat.SUMMARY: 'SUMMARY'>,
 |      expectation_parameters: 'Optional[SuiteParameterDict]' = None
 |  ) -> 'ExpectationValidationResult | ExpectationSuiteValidationResult'
 |      --Public API--
 |      Validate the Batch using the provided Expectation or Expectation Suite.
 |
 |      Args:
 |          expect: The Expectation or Expectation Suite to validate.
 |          result_format: The format to return the validation results in.
 |          expectation_parameters: A dictionary of parameters values for any
 |                                  expectations using parameterized values (the $PARAMETER syntax).
 |                                  The keys are the parameter names and the values are the values
 |                                  to be used for this validation run.
 |
 |      Returns:
 |          An ExpectationValidationResult or ExpectationSuiteValidationResult object.
 |
 |      Raises:
 |          ValueError: If the expect argument is not an Expectation or an ExpectationSuite.
 |
 |  ----------------------------------------------------------------------
 |  Readonly properties defined here:
 |
 |  batch_definition
 |
 |  batch_markers
 |
 |  batch_request
 |
 |  batch_spec
 |
 |  data
 |
 |  data_asset
 |
 |  datasource
 |
 |  id
 |
 |  ----------------------------------------------------------------------
 |  Data descriptors defined here:
 |
 |  __dict__
 |      dictionary for instance variables
 |
 |  __weakref__
 |      list of weak references to the object

None

In [24]:
print(type(batch.data))

<class 'great_expectations.execution_engine.pandas_batch_data.PandasBatchData'>

In [25]:
batch.data.head()

Empty DataFrame
Columns: []
Index: []

## creating expectation

In [26]:

suite = context.suites.add(
    gx.ExpectationSuite(name='customer_quality_suite_v1')

)
print(suite)

DataContextError: Cannot add ExpectationSuite with name customer_quality_suite_v1 because it already exists.

## add expectations

In [ ]:
expectation  = gx.expectations.ExpectColumnValuesToNotBeNull(
    column = 'customer_id'
)

In [ ]:
expectation

ExpectColumnValuesToNotBeNull(id=None, meta=None, notes=None, result_format=<ResultFormat.BASIC: 'BASIC'>, description=None, catch_exceptions=True, rendered_content=None, severity=<FailureSeverity.CRITICAL: 'critical'>, windows=None, batch_id=None, column='customer_id', mostly=1, row_condition=None, condition_parser=None)

In [ ]:
suite.add_expectation(expectation)

ExpectColumnValuesToNotBeNull(id='602d8e76-98a7-4b33-9c58-3b821e1ac62d', meta=None, notes=None, result_format=<ResultFormat.BASIC: 'BASIC'>, description=None, catch_exceptions=True, rendered_content=None, severity=<FailureSeverity.CRITICAL: 'critical'>, windows=None, batch_id=None, column='customer_id', mostly=1, row_condition=None, condition_parser=None)

In [ ]:
suite

{
  "name": "customer_quality_suite_v1",
  "id": "f00466fd-f13f-4c73-9ffc-2e58136e66fd",
  "expectations": [
    {
      "type": "expect_column_values_to_not_be_null",
      "kwargs": {
        "column": "customer_id"
      },
      "meta": {},
      "id": "602d8e76-98a7-4b33-9c58-3b821e1ac62d",
      "severity": "critical"
    }
  ],
  "meta": {
    "great_expectations_version": "1.23.1"
  },
  "notes": null
}

In [ ]:
unique_expectation = gx.expectations.ExpectColumnValuesToBeUnique(
    column = 'customer_id'
)

In [ ]:
suite.add_expectation(unique_expectation)

ExpectColumnValuesToBeUnique(id='cbf63011-d237-40f0-9607-614a456da495', meta=None, notes=None, result_format=<ResultFormat.BASIC: 'BASIC'>, description=None, catch_exceptions=True, rendered_content=None, severity=<FailureSeverity.CRITICAL: 'critical'>, windows=None, batch_id=None, column='customer_id', mostly=1, row_condition=None, condition_parser=None)

In [ ]:
suite

{
  "name": "customer_quality_suite_v1",
  "id": "f00466fd-f13f-4c73-9ffc-2e58136e66fd",
  "expectations": [
    {
      "type": "expect_column_values_to_not_be_null",
      "kwargs": {
        "column": "customer_id"
      },
      "meta": {},
      "id": "602d8e76-98a7-4b33-9c58-3b821e1ac62d",
      "severity": "critical"
    },
    {
      "type": "expect_column_values_to_be_unique",
      "kwargs": {
        "column": "customer_id"
      },
      "meta": {},
      "id": "cbf63011-d237-40f0-9607-614a456da495",
      "severity": "critical"
    }
  ],
  "meta": {
    "great_expectations_version": "1.23.1"
  },
  "notes": null
}

In [ ]:
print(dir(gx.expectations.ExpectColumnValuesToBeBetween))

['Config', '__abstractmethods__', '__annotations__', '__class__', '__class_vars__', '__config__', '__copy__', '__custom_root_type__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__exclude_fields__', '__fields__', '__fields_set__', '__firstlineno__', '__format__', '__ge__', '__get_validators__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__include_fields__', '__init__', '__init_subclass__', '__iter__', '__json_encoder__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__post_root_validators__', '__pre_root_validators__', '__pretty__', '__private_attributes__', '__reduce__', '__reduce_ex__', '__repr__', '__repr_args__', '__repr_name__', '__repr_str__', '__rich_repr__', '__schema_cache__', '__setattr__', '__setstate__', '__signature__', '__sizeof__', '__slots__', '__static_attributes__', '__str__', '__subclasshook__', '__try_update_forward_refs__', '__validators__', '_abc_impl', '_add_array_params', '_add_mostly_pct_param', '_atomic_diagnostic_observed_value', '_build_evr', '_calculate_keys', '_copy_and_set_values', '_decompose_class', '_diagnostic_failed', '_diagnostic_meta_properties_renderer', '_diagnostic_observed_value_renderer', '_diagnostic_status_icon_renderer', '_diagnostic_unexpected_statement_renderer', '_diagnostic_unexpected_table_renderer', '_enforce_dict_if_root', '_get_array_string', '_get_default_value', '_get_domain_kwargs', '_get_observed_value_from_evr', '_get_result_format', '_get_runtime_kwargs', '_get_strict_max_string', '_get_strict_min_string', '_get_success_kwarg', '_get_success_kwargs', '_get_value', '_include_rendered_content', '_init_private_attributes', '_iter', '_library_metadata', '_prescriptive_failed', '_prescriptive_renderer', '_prescriptive_summary', '_prescriptive_template', '_register_renderer_functions', '_save_callback', '_to_normalized_self_dict', '_transform_legacy_row_condition', '_validate', '_validate_metric_value_between', '_validate_result_format', '_validate_row_condition', '_warn_if_result_format_config_in_expectation_configuration', '_warn_if_result_format_config_in_runtime_configuration', 'args_keys', 'check_min_val_or_max_val', 'configuration', 'construct', 'copy', 'dict', 'domain_keys', 'domain_type', 'examples', 'expectation_type', 'from_orm', 'get_allowed_config_keys', 'get_validation_dependencies', 'is_abstract', 'json', 'library_metadata', 'map_metric', 'metric_dependencies', 'metrics_validate', 'parse_file', 'parse_obj', 'parse_raw', 'print_diagnostic_checklist', 'register_save_callback', 'render', 'run_diagnostics', 'runtime_keys', 'save', 'schema', 'schema_json', 'success_keys', 'suite_parameter_options', 'update_forward_refs', 'validate', 'validate_', 'validate_configuration', 'version']

In [ ]:
help(gx.expectations.ExpectColumnValuesToBeBetween)

Help on class ExpectColumnValuesToBeBetween in module great_expectations.expectations.core.expect_column_values_to_be_between:

class ExpectColumnValuesToBeBetween(great_expectations.expectations.expectation.ColumnMapExpectation)
 |  ExpectColumnValuesToBeBetween(
 |      *,
 |      id: Optional[str] = None,
 |      meta: Optional[dict] = None,
 |      notes: Union[str, List[str], NoneType] = None,
 |      result_format: Union[great_expectations.core.result_format.ResultFormat, dict] = <ResultFormat.BASIC: 'BASIC'>,
 |      description: Optional[str] = None,
 |      catch_exceptions: bool = True,
 |      rendered_content: Optional[List[great_expectations.render.components.RenderedAtomicContent]] = None,
 |      severity: great_expectations.expectations.metadata_types.FailureSeverity = <FailureSeverity.CRITICAL: 'critical'>,
 |      windows: Optional[List[great_expectations.expectations.window.Window]] = None,
 |      batch_id: Optional[str] = None,
 |      column: pydantic.v1.schema.StrictStr,
 |      mostly: Union[pydantic.v1.types.ConstrainedFloatValue, dict] = 1,
 |      row_condition: Union[str, great_expectations.expectations.row_conditions.ComparisonCondition, great_expectations.expectations.row_conditions.NullityCondition, great_expectations.expectations.row_conditions.AndCondition, great_expectations.expectations.row_conditions.OrCondition, great_expectations.expectations.row_conditions.PassThroughCondition, NoneType] = None,
 |      condition_parser: Optional[Literal['great_expectations', 'great_expectations__experimental__', 'pandas', 'spark']] = None,
 |      min_value: Union[float, dict, datetime.date, datetime.datetime, NoneType] = None,
 |      max_value: Union[float, dict, datetime.date, datetime.datetime, NoneType] = None,
 |      strict_min: Union[bool, dict] = False,
 |      strict_max: Union[bool, dict] = False
 |  ) -> None
 |
 |  Expect the column entries to be between a minimum value and a maximum value (inclusive).
 |
 |  ExpectColumnValuesToBeBetween is a     Column Map Expectation
 |
 |  Column Map Expectations are one of the most common types of Expectation.
 |  They are evaluated for a single column and ask a yes/no question for every row in that column.
 |  Based on the result, they then calculate the percentage of rows that gave a positive answer. If the percentage is high enough, the Expectation considers that data valid.
 |
 |  Args:
 |      column (str):             The column name.
 |      min_value (comparable type or None):         The minimum value for a column entry.
 |      max_value (comparable type or None):         The maximum value for a column entry.
 |      strict_min (boolean):             If True, values must be strictly larger than min_value. Default=False.
 |      strict_max (boolean):             If True, values must be strictly smaller than max_value. Default=False.
 |
 |  Other Parameters:
 |      mostly (None or a float between 0 and 1):             Successful if at least `mostly` fraction of values match the Expectation.             For more detail, see [mostly](https://docs.greatexpectations.io/docs/reference/expectations/standard_arguments/#mostly).
 |      result_format (str or None):             Which output mode to use: BOOLEAN_ONLY, BASIC, COMPLETE, or SUMMARY.             For more detail, see [result_format](https://docs.greatexpectations.io/docs/reference/expectations/result_format).
 |      catch_exceptions (boolean or None):             If True, then catch exceptions and include them as part of the result object.             For more detail, see [catch_exceptions](https://docs.greatexpectations.io/docs/reference/expectations/standard_arguments/#catch_exceptions).
 |      meta (dict or None):             A JSON-serializable dictionary (nesting allowed) that will be included in the output without             modification. For more detail, see [meta](https://docs.greatexpectations.io/docs/reference/expectations/standard_arguments/#meta).
 |      severity (str or None):             The impact of this Expectation failing: critical, warning, or info. Defaults to critical if not set. Severity levels can be used to trigger different alerting patterns and actions.             For more detail, see [failure severity](https://docs.greatexpectations.io/docs/cloud/expectations/expectations_overview/#failure-severity).
 |
 |  Returns:
 |      An [ExpectationSuiteValidationResult](https://docs.greatexpectations.io/docs/terms/validation_result)
 |
 |      Exact fields vary depending on the values passed to result_format, catch_exceptions, and meta.
 |
 |  Notes:
 |      * min_value and max_value are both inclusive unless strict_min or strict_max are set to True.
 |      * If min_value is None, then max_value is treated as an upper bound, and there is no minimum value checked.
 |      * If max_value is None, then min_value is treated as a lower bound, and there is no maximum value checked.
 |
 |  See Also:
 |      [ExpectColumnValueLengthsToBeBetween](https://greatexpectations.io/expectations/expect_column_value_lengths_to_be_between)
 |
 |  Supported Data Sources:
 |      [Pandas](https://docs.greatexpectations.io/docs/application_integration_support/)
 |      [Spark](https://docs.greatexpectations.io/docs/application_integration_support/)
 |      [SQLite](https://docs.greatexpectations.io/docs/application_integration_support/)
 |      [PostgreSQL](https://docs.greatexpectations.io/docs/application_integration_support/)
 |      [Amazon Aurora PostgreSQL](https://docs.greatexpectations.io/docs/application_integration_support/)
 |      [Citus](https://docs.greatexpectations.io/docs/application_integration_support/)
 |      [AlloyDB](https://docs.greatexpectations.io/docs/application_integration_support/)
 |      [Neon](https://docs.greatexpectations.io/docs/application_integration_support/)
 |      [MySQL](https://docs.greatexpectations.io/docs/application_integration_support/)
 |      [SQL Server](https://docs.greatexpectations.io/docs/application_integration_support/)
 |      [BigQuery](https://docs.greatexpectations.io/docs/application_integration_support/)
 |      [Snowflake](https://docs.greatexpectations.io/docs/application_integration_support/)
 |      [Databricks (SQL)](https://docs.greatexpectations.io/docs/application_integration_support/)
 |
 |  Data Quality Issues:
 |      Numeric
 |
 |  Example Data:
 |              test    test2
 |          0   1       1
 |          1   1.3     7
 |          2   .8      2.5
 |          3   2       3
 |
 |  Code Examples:
 |      Passing Case:
 |          Input:
 |              ExpectColumnValuesToBeBetween(
 |                  column="test",
 |                  min_value=.5,
 |                  max_value=2
 |          )
 |
 |          Output:
 |              {
 |                "exception_info": {
 |                  "raised_exception": false,
 |                  "exception_traceback": null,
 |                  "exception_message": null
 |                },
 |                "result": {
 |                  "element_count": 4,
 |                  "unexpected_count": 0,
 |                  "unexpected_percent": 0.0,
 |                  "partial_unexpected_list": [],
 |                  "missing_count": 0,
 |                  "missing_percent": 0.0,
 |                  "unexpected_percent_total": 0.0,
 |                  "unexpected_percent_nonmissing": 0.0
 |                },
 |                "meta": {},
 |                "success": true
 |              }
 |
 |      Failing Case:
 |          Input:
 |              ExpectColumnValuesToBeBetween(
 |                  column="test2",
 |                  min_value=1,
 |                  max_value=7,
 |                  strict_min=False,
 |                  strict_max=True
 |          )
 |
 |          Output:
 |              {
 |                "exception_info": {
 |                  "raised_exception": false,
 |                  "exception_traceback": null,
 |                  "exception_message": null
 |                },
 |                "result": {
 |                  "element_count": 4,
 |                  "unexpected_count": 1,
 |                  "unexpected_percent": 25.0,
 |                  "partial_unexpected_list": [
 |                    7.0
 |                  ],
 |                  "missing_count": 0,
 |                  "missing_percent": 0.0,
 |                  "unexpected_percent_total": 25.0,
 |                  "unexpected_percent_nonmissing": 25.0
 |                },
 |                "meta": {},
 |                "success": false
 |              }
 |
 |  Method resolution order:
 |      ExpectColumnValuesToBeBetween
 |      great_expectations.expectations.expectation.ColumnMapExpectation
 |      great_expectations.expectations.expectation.BatchExpectation
 |      great_expectations.expectations.expectation.Expectation
 |      pydantic.v1.main.BaseModel
 |      pydantic.v1.utils.Representation
 |      abc.ABC
 |      builtins.object
 |
 |  Methods defined here:
 |
 |  __hash__(self) -> 'int' from great_expectations.expectations.expectation.Expectation
 |      Return hash(self).
 |
 |  ----------------------------------------------------------------------
 |  Class methods defined here:
 |
 |  check_min_val_or_max_val(values: 'dict') -> 'dict'
 |
 |  ----------------------------------------------------------------------
 |  Static methods defined here:
 |
 |  __json_encoder__ = functools.partial(<function custom_pydantic_enco...ectation.Config.<lambda> at 0x000001FEAECAEE80>})
 |  ----------------------------------------------------------------------
 |  Data and other attributes defined here:
 |
 |  Config = <class 'great_expectations.expectations.core.exp...be_between...
 |
 |  __abstractmethods__ = frozenset()
 |
 |  __annotations__ = {'library_metadata': 'ClassVar[Dict[str, Union[str, ...
 |
 |  __class_vars__ = {'args_keys', 'domain_keys', 'domain_type', 'examples...
 |
 |  __config__ = <class 'pydantic.v1.config.Config'>
 |
 |  __custom_root_type__ = False
 |
 |  __exclude_fields__ = None
 |
 |  __fields__ = {'batch_id': ModelField(name='batch_id', type=Optional[st...
 |
 |  __include_fields__ = None
 |
 |  __post_root_validators__ = [(False, <function Expectation._transform_l...
 |
 |  __pre_root_validators__ = []
 |
 |  __private_attributes__ = {'_save_callback': ModelPrivateAttr()}
 |
 |  __schema_cache__ = {}
 |
 |  __signature__ = <Signature (*, id: Optional[str] = None, meta: O..., s...
 |
 |  __validators__ = {'result_format': [<pydantic.v1.class_validators.Vali...
 |
 |  args_keys = ('column', 'min_value', 'max_value', 'strict_min', 'strict...
 |
 |  expectation_type = 'expect_column_values_to_be_between'
 |
 |  library_metadata = {'contributors': ['@great_expectations'], 'has_full...
 |
 |  map_metric = 'column_values.between'
 |
 |  success_keys = ('min_value', 'max_value', 'strict_min', 'strict_max', ...
 |
 |  ----------------------------------------------------------------------
 |  Methods inherited from great_expectations.expectations.expectation.ColumnMapExpectation:
 |
 |  get_validation_dependencies(
 |      self,
 |      execution_engine: 'Optional[ExecutionEngine]' = None,
 |      runtime_configuration: 'Optional[dict]' = None,
 |      **kwargs: 'dict'
 |  ) -> 'ValidationDependencies'
 |      Returns the result format and metrics required to validate this Expectation using the provided result format.
 |
 |  ----------------------------------------------------------------------
 |  Class methods inherited from great_expectations.expectations.expectation.ColumnMapExpectation:
 |
 |  is_abstract() -> 'bool'
 |
 |  ----------------------------------------------------------------------
 |  Data and other attributes inherited from great_expectations.expectations.expectation.ColumnMapExpectation:
 |
 |  domain_keys = ('batch_id', 'column', 'row_condition', 'condition_parse...
 |
 |  domain_type = <MetricDomainTypes.COLUMN: 'column'>
 |
 |  ----------------------------------------------------------------------
 |  Data and other attributes inherited from great_expectations.expectations.expectation.BatchExpectation:
 |
 |  metric_dependencies = ()
 |
 |  ----------------------------------------------------------------------
 |  Methods inherited from great_expectations.expectations.expectation.Expectation:
 |
 |  __copy__(self)
 |
 |  __eq__(self, other: 'object') -> 'bool'
 |      Return self==value.
 |
 |  __lt__(self, other: 'object') -> 'bool'
 |      Return self<value.
 |
 |  metrics_validate(
 |      self,
 |      metrics: 'dict',
 |      runtime_configuration: 'Optional[dict]' = None,
 |      execution_engine: 'Optional[ExecutionEngine]' = None,
 |      **kwargs: 'dict'
 |  ) -> 'ExpectationValidationResult'
 |      # noinspection PyUnusedLocal
 |
 |  print_diagnostic_checklist(
 |      self,
 |      diagnostics: 'Optional[ExpectationDiagnostics]' = None,
 |      show_failed_tests: 'bool' = False,
 |      backends: 'Optional[List[str]]' = None,
 |      show_debug_messages: 'bool' = False
 |  ) -> 'str'
 |      --Public API--Runs self.run_diagnostics and generates a diagnostic checklist.
 |
 |      This output from this method is a thin wrapper for ExpectationDiagnostics.generate_checklist()
 |      This method is experimental.
 |
 |      Args:
 |          diagnostics (optional[ExpectationDiagnostics]): If diagnostics are not provided, diagnostics will be ran on self.
 |          show_failed_tests (bool): If true, failing tests will be printed.
 |          backends: list of backends to pass to run_diagnostics
 |          show_debug_messages (bool): If true, create a logger and pass to run_diagnostics
 |
 |  register_save_callback(
 |      self,
 |      save_callback: 'Callable[[Expectation], Expectation]'
 |  ) -> 'None'
 |
 |  render(self) -> 'None'
 |      Renders content using the atomic prescriptive renderer for each expectation configuration associated with
 |         this ExpectationSuite to ExpectationConfiguration.rendered_content.
 |
 |  run_diagnostics(
 |      self,
 |      raise_exceptions_for_backends: 'bool' = False,
 |      ignore_suppress: 'bool' = False,
 |      ignore_only_for: 'bool' = False,
 |      for_gallery: 'bool' = False,
 |      debug_logger: 'Optional[logging.Logger]' = None,
 |      only_consider_these_backends: 'Optional[List[str]]' = None,
 |      context: 'Optional[AbstractDataContext]' = None
 |  ) -> 'ExpectationDiagnostics'
 |      --Public API--Produce a diagnostic report about this Expectation.
 |
 |      The current uses for this method's output are
 |      using the JSON structure to populate the Public Expectation Gallery
 |      and enabling a fast dev loop for developing new Expectations where the
 |      contributors can quickly check the completeness of their expectations.
 |
 |      The contents of the report are captured in the ExpectationDiagnostics dataclass.
 |      You can see some examples in test_expectation_diagnostics.py
 |
 |      Some components (e.g. description, examples, library_metadata) of the diagnostic report can be introspected directly from the Exepctation class.
 |      Other components (e.g. metrics, renderers, executions) are at least partly dependent on instantiating, validating, and/or executing the Expectation class.
 |      For these kinds of components, at least one test case with include_in_gallery=True must be present in the examples to
 |      produce the metrics, renderers and execution engines parts of the report. This is due to
 |      a get_validation_dependencies requiring expectation_config as an argument.
 |
 |      If errors are encountered in the process of running the diagnostics, they are assumed to be due to
 |      incompleteness of the Expectation's implementation (e.g., declaring a dependency on Metrics
 |      that do not exist). These errors are added under "errors" key in the report.
 |
 |      Args:
 |          raise_exceptions_for_backends: Bool object that when True will raise an Exception if a backend fails to connect.
 |          ignore_suppress:  Bool object that when True will ignore the suppress_test_for list on Expectation sample tests.
 |          ignore_only_for:  Bool object that when True will ignore the only_for list on Expectation sample tests.
 |          for_gallery:  Bool object that when True will create empty arrays to use as examples for the Expectation Diagnostics.
 |          debug_logger (optional[logging.Logger]):  Logger object to use for sending debug messages to.
 |          only_consider_these_backends (optional[List[str]])  List of backends to consider.
 |          context (optional[AbstractDataContext]): Instance of any child of "AbstractDataContext" class.
 |
 |      Returns:
 |          An Expectation Diagnostics report object
 |
 |  save(self)
 |      --Public API--Save the current state of this Expectation.
 |
 |  validate_(
 |      self,
 |      validator: 'Validator',
 |      suite_parameters: 'Optional[dict]' = None,
 |      interactive_evaluation: 'bool' = True,
 |      data_context: 'Optional[AbstractDataContext]' = None,
 |      runtime_configuration: 'Optional[dict]' = None
 |  ) -> 'ExpectationValidationResult'
 |      Validates the expectation against the provided data.
 |
 |      Args:
 |          validator: A Validator object that can be used to create Expectations, validate Expectations,
 |              and get Metrics for Expectations.
 |          suite_parameters: Dictionary of dynamic values used during Validation of an Expectation.
 |          interactive_evaluation: Setting the interactive_evaluation flag on a DataAsset
 |              make it possible to declare expectations and store expectations without
 |              immediately evaluating them.
 |          data_context: An instance of a GX DataContext.
 |          runtime_configuration: The runtime configuration for the Expectation.
 |      Returns:
 |          An ExpectationValidationResult object
 |
 |  validate_configuration(
 |      self,
 |      configuration: 'Optional[ExpectationConfiguration]' = None
 |  ) -> 'None'
 |
 |  ----------------------------------------------------------------------
 |  Class methods inherited from great_expectations.expectations.expectation.Expectation:
 |
 |  get_allowed_config_keys() -> 'Union[Tuple[str, ...], Tuple[str]]'
 |
 |  ----------------------------------------------------------------------
 |  Readonly properties inherited from great_expectations.expectations.expectation.Expectation:
 |
 |  configuration
 |
 |  suite_parameter_options
 |      SuiteParameter options for this Expectation.
 |
 |      Returns:
 |          tuple[str, ...]: The keys of the suite parameters used in this Expectation at runtime.
 |
 |  ----------------------------------------------------------------------
 |  Data and other attributes inherited from great_expectations.expectations.expectation.Expectation:
 |
 |  examples = []
 |
 |  runtime_keys = ('catch_exceptions', 'result_format')
 |
 |  version = '1.23.1'
 |
 |  ----------------------------------------------------------------------
 |  Methods inherited from pydantic.v1.main.BaseModel:
 |
 |  __getstate__(self) -> 'DictAny'
 |      Helper for pickle.
 |
 |  __init__(__pydantic_self__, **data: Any) -> None
 |      Create a new model by parsing and validating input data from keyword arguments.
 |
 |      Raises ValidationError if the input data cannot be parsed to form a valid model.
 |
 |  __iter__(self) -> 'TupleGenerator'
 |      so `dict(model)` works
 |
 |  __repr_args__(self) -> 'ReprArgs'
 |      Returns the attributes to show in __str__, __repr__, and __pretty__ this is generally overridden.
 |
 |      Can either return:
 |      * name - value pairs, e.g.: `[('foo_name', 'foo'), ('bar_name', ['b', 'a', 'r'])]`
 |      * or, just values, e.g.: `[(None, 'foo'), (None, ['b', 'a', 'r'])]`
 |
 |  __setattr__(self, name, value)
 |      Implement setattr(self, name, value).
 |
 |  __setstate__(self, state: 'DictAny') -> None
 |
 |  copy(

In [ ]:
#age between
age_between = gx.expectations.ExpectColumnValuesToBeBetween(
    column='age'
    ,min_value = 18
    ,max_value = 100

)

In [ ]:
suite.add_expectation(age_between)

ExpectColumnValuesToBeBetween(id='dfab93aa-7b3d-46a0-8d72-a62f6ae2cdf6', meta=None, notes=None, result_format=<ResultFormat.BASIC: 'BASIC'>, description=None, catch_exceptions=True, rendered_content=None, severity=<FailureSeverity.CRITICAL: 'critical'>, windows=None, batch_id=None, column='age', mostly=1, row_condition=None, condition_parser=None, min_value=18.0, max_value=100.0, strict_min=False, strict_max=False)

In [ ]:
print(suite)

{
  "name": "customer_quality_suite_v1",
  "id": "f00466fd-f13f-4c73-9ffc-2e58136e66fd",
  "expectations": [
    {
      "type": "expect_column_values_to_not_be_null",
      "kwargs": {
        "column": "customer_id"
      },
      "meta": {},
      "id": "602d8e76-98a7-4b33-9c58-3b821e1ac62d",
      "severity": "critical"
    },
    {
      "type": "expect_column_values_to_be_unique",
      "kwargs": {
        "column": "customer_id"
      },
      "meta": {},
      "id": "cbf63011-d237-40f0-9607-614a456da495",
      "severity": "critical"
    },
    {
      "type": "expect_column_values_to_be_between",
      "kwargs": {
        "column": "age",
        "min_value": 18.0,
        "max_value": 100.0
      },
      "meta": {},
      "id": "dfab93aa-7b3d-46a0-8d72-a62f6ae2cdf6",
      "severity": "critical"
    }
  ],
  "meta": {
    "great_expectations_version": "1.23.1"
  },
  "notes": null
}

In [ ]:
help(gx.expectations.ExpectColumnDistinctValuesToBeInSet)

Help on class ExpectColumnDistinctValuesToBeInSet in module great_expectations.expectations.core.expect_column_distinct_values_to_be_in_set:

class ExpectColumnDistinctValuesToBeInSet(great_expectations.expectations.expectation.ColumnAggregateExpectation)
 |  ExpectColumnDistinctValuesToBeInSet(
 |      *,
 |      id: Optional[str] = None,
 |      meta: Optional[dict] = None,
 |      notes: Union[str, List[str], NoneType] = None,
 |      result_format: Union[great_expectations.core.result_format.ResultFormat, dict] = <ResultFormat.BASIC: 'BASIC'>,
 |      description: Optional[str] = None,
 |      catch_exceptions: bool = False,
 |      rendered_content: Optional[List[great_expectations.render.components.RenderedAtomicContent]] = None,
 |      severity: great_expectations.expectations.metadata_types.FailureSeverity = <FailureSeverity.CRITICAL: 'critical'>,
 |      windows: Optional[List[great_expectations.expectations.window.Window]] = None,
 |      batch_id: Optional[str] = None,
 |      column: pydantic.v1.schema.StrictStr,
 |      row_condition: Union[str, great_expectations.expectations.row_conditions.ComparisonCondition, great_expectations.expectations.row_conditions.NullityCondition, great_expectations.expectations.row_conditions.AndCondition, great_expectations.expectations.row_conditions.OrCondition, great_expectations.expectations.row_conditions.PassThroughCondition, NoneType] = None,
 |      condition_parser: Optional[Literal['great_expectations', 'great_expectations__experimental__', 'pandas', 'spark']] = None,
 |      value_set: Annotated[Union[List, dict], FieldInfo(default=PydanticUndefined, title='Value Set', description='A set of objects used for comparison.', extra={'schema_overrides': {'anyOf': [{'title': 'Value Set', 'description': 'A set of objects used for comparison.', 'oneOf': [{'title': 'Text', 'type': 'array', 'items': {'type': 'string', 'minLength': 1}, 'minItems': 1, 'examples': [['a', 'b', 'c', 'd', 'e'], ['2024-01-01', '2024-01-02', '2024-01-03', '2024-01-04', '2024-01-05']]}, {'title': 'Numbers', 'type': 'array', 'items': {'type': 'number'}, 'minItems': 1, 'examples': [[1, 2, 3, 4, 5], [1.1, 2.2, 3.3, 4.4, 5.5], [1, 2.2, 3, 4.4, 5]]}]}, {'type': 'object'}]}})]
 |  ) -> None
 |
 |  Expect the set of distinct column values to be contained by a given set.
 |
 |  ExpectColumnDistinctValuesToBeInSet is a     Column Aggregate Expectation.
 |
 |  Column Aggregate Expectations are one of the most common types of Expectation.
 |  They are evaluated for a single column, and produce an aggregate Metric, such as a mean, standard deviation, number of unique values, column type, etc.
 |  If that Metric meets the conditions you set, the Expectation considers that data valid.
 |
 |  Args:
 |      column (str):             The column name.
 |      value_set (set-like):             A set of objects used for comparison.
 |
 |  Other Parameters:
 |      result_format (str or None):             Which output mode to use: BOOLEAN_ONLY, BASIC, COMPLETE, or SUMMARY.             For more detail, see [result_format](https://docs.greatexpectations.io/docs/reference/expectations/result_format).
 |      catch_exceptions (boolean or None):             If True, then catch exceptions and include them as part of the result object.             For more detail, see [catch_exceptions](https://docs.greatexpectations.io/docs/reference/expectations/standard_arguments/#catch_exceptions).
 |      meta (dict or None):             A JSON-serializable dictionary (nesting allowed) that will be included in the output without             modification. For more detail, see [meta](https://docs.greatexpectations.io/docs/reference/expectations/standard_arguments/#meta).
 |      severity (str or None):             The impact of this Expectation failing: critical, warning, or info. Defaults to critical if not set. Severity levels can be used to trigger different alerting patterns and actions.             For more detail, see [failure severity](https://docs.greatexpectations.io/docs/cloud/expectations/expectations_overview/#failure-severity).
 |
 |  Returns:
 |      An [ExpectationSuiteValidationResult](https://docs.greatexpectations.io/docs/terms/validation_result)
 |
 |      Exact fields vary depending on the values passed to result_format, catch_exceptions, and meta.
 |
 |  Notes:
 |      The success value for this expectation will match that of     [ExpectColumnValuesToBeInSet](https://greatexpectations.io/expectations/expect_column_values_to_be_in_set).
 |      The observed_value field is always None. To inspect violations, use unexpected_count and     partial_unexpected_list (distinct column values not in value_set, capped at 20). When the     Expectation passes, partial_unexpected_list is empty.
 |
 |  See Also:
 |      [ExpectColumnDistinctValuesToContainSet](https://greatexpectations.io/expectations/expect_column_distinct_values_to_contain_set)
 |      [ExpectColumnDistinctValuesToEqualSet](https://greatexpectations.io/expectations/expect_column_distinct_values_to_equal_set)
 |
 |  Supported Data Sources:
 |      [Pandas](https://docs.greatexpectations.io/docs/application_integration_support/)
 |      [Spark](https://docs.greatexpectations.io/docs/application_integration_support/)
 |      [SQLite](https://docs.greatexpectations.io/docs/application_integration_support/)
 |      [PostgreSQL](https://docs.greatexpectations.io/docs/application_integration_support/)
 |      [Amazon Aurora PostgreSQL](https://docs.greatexpectations.io/docs/application_integration_support/)
 |      [Citus](https://docs.greatexpectations.io/docs/application_integration_support/)
 |      [AlloyDB](https://docs.greatexpectations.io/docs/application_integration_support/)
 |      [Neon](https://docs.greatexpectations.io/docs/application_integration_support/)
 |      [MySQL](https://docs.greatexpectations.io/docs/application_integration_support/)
 |      [SQL Server](https://docs.greatexpectations.io/docs/application_integration_support/)
 |      [BigQuery](https://docs.greatexpectations.io/docs/application_integration_support/)
 |      [Snowflake](https://docs.greatexpectations.io/docs/application_integration_support/)
 |      [Databricks (SQL)](https://docs.greatexpectations.io/docs/application_integration_support/)
 |      [Redshift](https://docs.greatexpectations.io/docs/application_integration_support/)
 |
 |  Data Quality Issues:
 |      Uniqueness
 |
 |  Example Data:
 |              test    test2
 |          0   1       1
 |          1   2       1
 |          2   4       1
 |
 |  Code Examples:
 |      Passing Case:
 |          Input:
 |              ExpectColumnDistinctValuesToBeInSet(
 |                  column="test",
 |                  value_set=[1, 2, 3, 4, 5]
 |          )
 |
 |          Output:
 |              {
 |                "exception_info": {
 |                  "raised_exception": false,
 |                  "exception_traceback": null,
 |                  "exception_message": null
 |                },
 |                "result": {
 |                  "observed_value": null,
 |                  "unexpected_count": 0,
 |                  "partial_unexpected_list": []
 |                },
 |                "meta": {},
 |                "success": true
 |              }
 |
 |      Failing Case:
 |          Input:
 |              ExpectColumnDistinctValuesToBeInSet(
 |                  column="test2",
 |                  value_set=[3, 2, 4]
 |          )
 |
 |          Output:
 |              {
 |                "exception_info": {
 |                  "raised_exception": false,
 |                  "exception_traceback": null,
 |                  "exception_message": null
 |                },
 |                "result": {
 |                  "observed_value": null,
 |                  "unexpected_count": 1,
 |                  "partial_unexpected_list": [
 |                    1
 |                  ]
 |                },
 |                "meta": {},
 |                "success": false
 |              }
 |
 |  Method resolution order:
 |      ExpectColumnDistinctValuesToBeInSet
 |      great_expectations.expectations.expectation.ColumnAggregateExpectation
 |      great_expectations.expectations.expectation.BatchExpectation
 |      great_expectations.expectations.expectation.Expectation
 |      pydantic.v1.main.BaseModel
 |      pydantic.v1.utils.Representation
 |      abc.ABC
 |      builtins.object
 |
 |  Methods defined here:
 |
 |  __hash__(self) -> 'int' from great_expectations.expectations.expectation.Expectation
 |      Return hash(self).
 |
 |  ----------------------------------------------------------------------
 |  Static methods defined here:
 |
 |  __json_encoder__ = functools.partial(<function custom_pydantic_enco...ectation.Config.<lambda> at 0x000001FEAECAEE80>})
 |  ----------------------------------------------------------------------
 |  Data and other attributes defined here:
 |
 |  Config = <class 'great_expectations.expectations.core.exp..._set.Expec...
 |
 |  __abstractmethods__ = frozenset()
 |
 |  __annotations__ = {'library_metadata': 'ClassVar[Dict[str, Union[str, ...
 |
 |  __class_vars__ = {'args_keys', 'domain_keys', 'domain_type', 'examples...
 |
 |  __config__ = <class 'pydantic.v1.config.Config'>
 |
 |  __custom_root_type__ = False
 |
 |  __exclude_fields__ = None
 |
 |  __fields__ = {'batch_id': ModelField(name='batch_id', type=Optional[st...
 |
 |  __include_fields__ = None
 |
 |  __post_root_validators__ = [(False, <function Expectation._transform_l...
 |
 |  __pre_root_validators__ = []
 |
 |  __private_attributes__ = {'_save_callback': ModelPrivateAttr()}
 |
 |  __schema_cache__ = {}
 |
 |  __signature__ = <Signature (*, id: Optional[str] = None, meta: O...3, ...
 |
 |  __validators__ = {'result_format': [<pydantic.v1.class_validators.Vali...
 |
 |  args_keys = ('column', 'value_set')
 |
 |  expectation_type = 'expect_column_distinct_values_to_be_in_set'
 |
 |  library_metadata = {'contributors': ['@great_expectations'], 'has_full...
 |
 |  metric_dependencies = ('column.distinct_values.not_in_set.count', 'col...
 |
 |  success_keys = ('value_set',)
 |
 |  ----------------------------------------------------------------------
 |  Data and other attributes inherited from great_expectations.expectations.expectation.ColumnAggregateExpectation:
 |
 |  domain_keys = ('batch_id', 'column', 'row_condition', 'condition_parse...
 |
 |  domain_type = <MetricDomainTypes.COLUMN: 'column'>
 |
 |  ----------------------------------------------------------------------
 |  Methods inherited from great_expectations.expectations.expectation.BatchExpectation:
 |
 |  get_validation_dependencies(
 |      self,
 |      execution_engine: 'Optional[ExecutionEngine]' = None,
 |      runtime_configuration: 'Optional[dict]' = None
 |  ) -> 'ValidationDependencies'
 |      Returns the result format and metrics required to validate this Expectation using the provided result format.
 |
 |  ----------------------------------------------------------------------
 |  Methods inherited from great_expectations.expectations.expectation.Expectation:
 |
 |  __copy__(self)
 |
 |  __eq__(self, other: 'object') -> 'bool'
 |      Return self==value.
 |
 |  __lt__(self, other: 'object') -> 'bool'
 |      Return self<value.
 |
 |  metrics_validate(
 |      self,
 |      metrics: 'dict',
 |      runtime_configuration: 'Optional[dict]' = None,
 |      execution_engine: 'Optional[ExecutionEngine]' = None,
 |      **kwargs: 'dict'
 |  ) -> 'ExpectationValidationResult'
 |      # noinspection PyUnusedLocal
 |
 |  print_diagnostic_checklist(
 |      self,
 |      diagnostics: 'Optional[ExpectationDiagnostics]' = None,
 |      show_failed_tests: 'bool' = False,
 |      backends: 'Optional[List[str]]' = None,
 |      show_debug_messages: 'bool' = False
 |  ) -> 'str'
 |      --Public API--Runs self.run_diagnostics and generates a diagnostic checklist.
 |
 |      This output from this method is a thin wrapper for ExpectationDiagnostics.generate_checklist()
 |      This method is experimental.
 |
 |      Args:
 |          diagnostics (optional[ExpectationDiagnostics]): If diagnostics are not provided, diagnostics will be ran on self.
 |          show_failed_tests (bool): If true, failing tests will be printed.
 |          backends: list of backends to pass to run_diagnostics
 |          show_debug_messages (bool): If true, create a logger and pass to run_diagnostics
 |
 |  register_save_callback(
 |      self,
 |      save_callback: 'Callable[[Expectation], Expectation]'
 |  ) -> 'None'
 |
 |  render(self) -> 'None'
 |      Renders content using the atomic prescriptive renderer for each expectation configuration associated with
 |         this ExpectationSuite to ExpectationConfiguration.rendered_content.
 |
 |  run_diagnostics(
 |      self,
 |      raise_exceptions_for_backends: 'bool' = False,
 |      ignore_suppress: 'bool' = False,
 |      ignore_only_for: 'bool' = False,
 |      for_gallery: 'bool' = False,
 |      debug_logger: 'Optional[logging.Logger]' = None,
 |      only_consider_these_backends: 'Optional[List[str]]' = None,
 |      context: 'Optional[AbstractDataContext]' = None
 |  ) -> 'ExpectationDiagnostics'
 |      --Public API--Produce a diagnostic report about this Expectation.
 |
 |      The current uses for this method's output are
 |      using the JSON structure to populate the Public Expectation Gallery
 |      and enabling a fast dev loop for developing new Expectations where the
 |      contributors can quickly check the completeness of their expectations.
 |
 |      The contents of the report are captured in the ExpectationDiagnostics dataclass.
 |      You can see some examples in test_expectation_diagnostics.py
 |
 |      Some components (e.g. description, examples, library_metadata) of the diagnostic report can be introspected directly from the Exepctation class.
 |      Other components (e.g. metrics, renderers, executions) are at least partly dependent on instantiating, validating, and/or executing the Expectation class.
 |      For these kinds of components, at least one test case with include_in_gallery=True must be present in the examples to
 |      produce the metrics, renderers and execution engines parts of the report. This is due to
 |      a get_validation_dependencies requiring expectation_config as an argument.
 |
 |      If errors are encountered in the process of running the diagnostics, they are assumed to be due to
 |      incompleteness of the Expectation's implementation (e.g., declaring a dependency on Metrics
 |      that do not exist). These errors are added under "errors" key in the report.
 |
 |      Args:
 |          raise_exceptions_for_backends: Bool object that when True will raise an Exception if a backend fails to connect.
 |          ignore_suppress:  Bool object that when True will ignore the suppress_test_for list on Expectation sample tests.
 |          ignore_only_for:  Bool object that when True will ignore the only_for list on Expectation sample tests.
 |          for_gallery:  Bool object that when True will create empty arrays to use as examples for the Expectation Diagnostics.
 |          debug_logger (optional[logging.Logger]):  Logger object to use for sending debug messages to.
 |          only_consider_these_backends (optional[List[str]])  List of backends to consider.
 |          context (optional[AbstractDataContext]): Instance of any child of "AbstractDataContext" class.
 |
 |      Returns:
 |          An Expectation Diagnostics report object
 |
 |  save(self)
 |      --Public API--Save the current state of this Expectation.
 |
 |  validate_(
 |      self,
 |      validator: 'Validator',
 |      suite_parameters: 'Optional[dict]' = None,
 |      interactive_evaluation: 'bool' = True,
 |      data_context: 'Optional[AbstractDataContext]' = None,
 |      runtime_configuration: 'Optional[dict]' = None
 |  ) -> 'ExpectationValidationResult'
 |      Validates the expectation against the provided data.
 |
 |      Args:
 |          validator: A Validator object that can be used to create Expectations, validate Expectations,
 |              and get Metrics for Expectations.
 |          suite_parameters: Dictionary of dynamic values used during Validation of an Expectation.
 |          interactive_evaluation: Setting the interactive_evaluation flag on a DataAsset
 |              make it possible to declare expectations and store expectations without
 |              immediately evaluating them.
 |          data_context: An instance of a GX DataContext.
 |          runtime_configuration: The runtime configuration for the Expectation.
 |      Returns:
 |          An ExpectationValidationResult object
 |
 |  validate_configuration(
 |      self,
 |      configuration: 'Optional[ExpectationConfiguration]' = None
 |  ) -> 'None'
 |
 |  ----------------------------------------------------------------------
 |  Class methods inherited from great_expectations.expectations.expectation.Expectation:
 |
 |  get_allowed_config_keys() -> 'Union[Tuple[str, ...], Tuple[str]]'
 |
 |  is_abstract() -> 'bool'
 |
 |  ----------------------------------------------------------------------
 |  Readonly properties inherited from great_expectations.expectations.expectation.Expectation:
 |
 |  configuration
 |
 |  suite_parameter_options
 |      SuiteParameter options for this Expectation.
 |
 |      Returns:
 |          tuple[str, ...]: The keys of the suite parameters used in this Expectation at runtime.
 |
 |  ----------------------------------------------------------------------
 |  Data and other attributes inherited from great_expectations.expectations.expectation.Expectation:
 |
 |  examples = []
 |
 |  runtime_keys = ('catch_exceptions', 'result_format')
 |
 |  version = '1.23.1'
 |
 |  ----------------------------------------------------------------------
 |  Methods inherited from pydantic.v1.main.BaseModel:
 |
 |  __getstate__(self) -> 'DictAny'
 |      Helper for pickle.
 |
 |  __init__(__pydantic_self__, **data: Any) -> None
 |      Create a new model by parsing and validating input data from keyword arguments.
 |
 |      Raises ValidationError if the input data cannot be parsed to form a valid model.
 |
 |  __iter__(self) -> 'TupleGenerator'
 |      so `dict(model)` works
 |
 |  __repr_args__(self) -> 'ReprArgs'
 |      Returns the attributes to show in __str__, __repr__, and __pretty__ this is generally overridden.
 |
 |      Can either return:
 |      * name - value pairs, e.g.: `[('foo_name', 'foo'), ('bar_name', ['b', 'a', 'r'])]`
 |      * or, just values, e.g.: `[(None, 'foo'), (None, ['b', 'a', 'r'])]`
 |
 |  __setattr__(self, name, value)
 |      Implement setattr(self, name, value).
 |
 |  __setstate__(self, state: 'DictAny') -> None
 |
 |  copy(
 |      self: 'Model',
 |      *,
 |      include: Union[ForwardRef('AbstractSetIntStr'), ForwardRef('MappingIntStrAny'), NoneType] = None,
 |      exclude: Union[ForwardRef('AbstractSetIntStr'), ForwardRef('MappingIntStrAny'), NoneType] = None,
 |      update: Optional[ForwardRef('DictStrAny')] = None,
 |      deep: bool = False
 |  ) -> 'Model'
 |      Duplicate a model, optionally choose which fields to include, exclude and change.
 |
 |      :param include: fields to include in new model
 |      :param exclude: fields to exclude from new model, as with values this takes precedence over include
 |      :param update: values to change/add in the new model. Note: the data is not validated before creating
 |          the new model: you should trust this data
 |      :param deep: set to `True` to make a deep copy of the model
 |      :return: new model instance
 |
 |  dict(
 |      self,
 |      *,
 |      include: Union[ForwardRef('AbstractSetIntStr'), ForwardRef('MappingIntStrAny'), NoneType] = None,
 |      exclude: Union[ForwardRef('AbstractSetIntStr'), ForwardRef('MappingIntStrAny'), NoneType] = None,
 |      by_alias: bool = False,

In [ ]:
status_allowed_values = gx.expectations.ExpectColumnDistinctValuesToBeInSet(
    column='status',
    value_set = ['active','inactive']
)

In [ ]:
suite.add_expectation(status_allowed_values)

ExpectColumnDistinctValuesToBeInSet(id='ae27598a-80b0-4062-a43c-aee3363fd43f', meta=None, notes=None, result_format=<ResultFormat.BASIC: 'BASIC'>, description=None, catch_exceptions=False, rendered_content=None, severity=<FailureSeverity.CRITICAL: 'critical'>, windows=None, batch_id=None, column='status', row_condition=None, condition_parser=None, value_set=['active', 'inactive'])

In [ ]:
suite

{
  "name": "customer_quality_suite_v1",
  "id": "f00466fd-f13f-4c73-9ffc-2e58136e66fd",
  "expectations": [
    {
      "type": "expect_column_values_to_not_be_null",
      "kwargs": {
        "column": "customer_id"
      },
      "meta": {},
      "id": "602d8e76-98a7-4b33-9c58-3b821e1ac62d",
      "severity": "critical"
    },
    {
      "type": "expect_column_values_to_be_unique",
      "kwargs": {
        "column": "customer_id"
      },
      "meta": {},
      "id": "cbf63011-d237-40f0-9607-614a456da495",
      "severity": "critical"
    },
    {
      "type": "expect_column_values_to_be_between",
      "kwargs": {
        "column": "age",
        "min_value": 18.0,
        "max_value": 100.0
      },
      "meta": {},
      "id": "dfab93aa-7b3d-46a0-8d72-a62f6ae2cdf6",
      "severity": "critical"
    },
    {
      "type": "expect_column_distinct_values_to_be_in_set",
      "kwargs": {
        "column": "status",
        "value_set": [
          "active",
          "inactive"
        ]
      },
      "meta": {},
      "id": "ae27598a-80b0-4062-a43c-aee3363fd43f",
      "severity": "critical"
    }
  ],
  "meta": {
    "great_expectations_version": "1.23.1"
  },
  "notes": null
}

In [ ]:
email_not_null = gx.expectations.ExpectColumnValuesToNotBeNull(
    column='email'

)
suite.add_expectation(email_not_null)
suite

{
  "name": "customer_quality_suite_v1",
  "id": "f00466fd-f13f-4c73-9ffc-2e58136e66fd",
  "expectations": [
    {
      "type": "expect_column_values_to_not_be_null",
      "kwargs": {
        "column": "customer_id"
      },
      "meta": {},
      "id": "602d8e76-98a7-4b33-9c58-3b821e1ac62d",
      "severity": "critical"
    },
    {
      "type": "expect_column_values_to_be_unique",
      "kwargs": {
        "column": "customer_id"
      },
      "meta": {},
      "id": "cbf63011-d237-40f0-9607-614a456da495",
      "severity": "critical"
    },
    {
      "type": "expect_column_values_to_be_between",
      "kwargs": {
        "column": "age",
        "min_value": 18.0,
        "max_value": 100.0
      },
      "meta": {},
      "id": "dfab93aa-7b3d-46a0-8d72-a62f6ae2cdf6",
      "severity": "critical"
    },
    {
      "type": "expect_column_distinct_values_to_be_in_set",
      "kwargs": {
        "column": "status",
        "value_set": [
          "active",
          "inactive"
        ]
      },
      "meta": {},
      "id": "ae27598a-80b0-4062-a43c-aee3363fd43f",
      "severity": "critical"
    },
    {
      "type": "expect_column_values_to_not_be_null",
      "kwargs": {
        "column": "email"
      },
      "meta": {},
      "id": "646bf99e-f1ca-4012-8491-eb4d507d9253",
      "severity": "critical"
    }
  ],
  "meta": {
    "great_expectations_version": "1.23.1"
  },
  "notes": null
}

In [ ]:
help(batch.validate)

Help on method validate in module great_expectations.datasource.fluent.interfaces:

validate(
    expect: 'Expectation | ExpectationSuite',
    *,
    result_format: 'ResultFormatUnion' = <ResultFormat.SUMMARY: 'SUMMARY'>,
    expectation_parameters: 'Optional[SuiteParameterDict]' = None
) -> 'ExpectationValidationResult | ExpectationSuiteValidationResult' method of great_expectations.datasource.fluent.interfaces.Batch instance
    --Public API--
    Validate the Batch using the provided Expectation or Expectation Suite.

    Args:
        expect: The Expectation or Expectation Suite to validate.
        result_format: The format to return the validation results in.
        expectation_parameters: A dictionary of parameters values for any
                                expectations using parameterized values (the $PARAMETER syntax).
                                The keys are the parameter names and the values are the values
                                to be used for this validation run.

    Returns:
        An ExpectationValidationResult or ExpectationSuiteValidationResult object.

    Raises:
        ValueError: If the expect argument is not an Expectation or an ExpectationSuite.

In [ ]:
validation_result = batch.validate(expect=suite)

Calculating Metrics: 100%|██████████| 27/27 [00:00<00:00, 981.09it/s]

In [ ]:
print(validation_result)

{
  "success": true,
  "results": [
    {
      "success": true,
      "expectation_config": {
        "type": "expect_column_values_to_not_be_null",
        "kwargs": {
          "batch_id": "customer_data_source-customer",
          "column": "customer_id"
        },
        "meta": {},
        "id": "602d8e76-98a7-4b33-9c58-3b821e1ac62d",
        "severity": "critical"
      },
      "result": {
        "element_count": 10,
        "unexpected_count": 0,
        "unexpected_percent": 0.0,
        "partial_unexpected_list": [],
        "partial_unexpected_counts": [],
        "partial_unexpected_index_list": []
      },
      "meta": {},
      "exception_info": {
        "raised_exception": false,
        "exception_traceback": null,
        "exception_message": null
      }
    },
    {
      "success": true,
      "expectation_config": {
        "type": "expect_column_values_to_be_unique",
        "kwargs": {
          "batch_id": "customer_data_source-customer",
          "column": "customer_id"
        },
        "meta": {},
        "id": "cbf63011-d237-40f0-9607-614a456da495",
        "severity": "critical"
      },
      "result": {
        "element_count": 10,
        "unexpected_count": 0,
        "unexpected_percent": 0.0,
        "partial_unexpected_list": [],
        "missing_count": 0,
        "missing_percent": 0.0,
        "unexpected_percent_total": 0.0,
        "unexpected_percent_nonmissing": 0.0,
        "partial_unexpected_counts": [],
        "partial_unexpected_index_list": []
      },
      "meta": {},
      "exception_info": {
        "raised_exception": false,
        "exception_traceback": null,
        "exception_message": null
      }
    },
    {
      "success": true,
      "expectation_config": {
        "type": "expect_column_values_to_be_between",
        "kwargs": {
          "batch_id": "customer_data_source-customer",
          "column": "age",
          "min_value": 18.0,
          "max_value": 100.0
        },
        "meta": {},
        "id": "dfab93aa-7b3d-46a0-8d72-a62f6ae2cdf6",
        "severity": "critical"
      },
      "result": {
        "element_count": 10,
        "unexpected_count": 0,
        "unexpected_percent": 0.0,
        "partial_unexpected_list": [],
        "missing_count": 0,
        "missing_percent": 0.0,
        "unexpected_percent_total": 0.0,
        "unexpected_percent_nonmissing": 0.0,
        "partial_unexpected_counts": [],
        "partial_unexpected_index_list": []
      },
      "meta": {},
      "exception_info": {
        "raised_exception": false,
        "exception_traceback": null,
        "exception_message": null
      }
    },
    {
      "success": true,
      "expectation_config": {
        "type": "expect_column_distinct_values_to_be_in_set",
        "kwargs": {
          "batch_id": "customer_data_source-customer",
          "column": "status",
          "value_set": [
            "active",
            "inactive"
          ]
        },
        "meta": {},
        "id": "ae27598a-80b0-4062-a43c-aee3363fd43f",
        "severity": "critical"
      },
      "result": {
        "observed_value": null,
        "unexpected_count": 0,
        "partial_unexpected_list": []
      },
      "meta": {},
      "exception_info": {
        "raised_exception": false,
        "exception_traceback": null,
        "exception_message": null
      }
    },
    {
      "success": true,
      "expectation_config": {
        "type": "expect_column_values_to_not_be_null",
        "kwargs": {
          "batch_id": "customer_data_source-customer",
          "column": "email"
        },
        "meta": {},
        "id": "646bf99e-f1ca-4012-8491-eb4d507d9253",
        "severity": "critical"
      },
      "result": {
        "element_count": 10,
        "unexpected_count": 0,
        "unexpected_percent": 0.0,
        "partial_unexpected_list": [],
        "partial_unexpected_counts": [],
        "partial_unexpected_index_list": []
      },
      "meta": {},
      "exception_info": {
        "raised_exception": false,
        "exception_traceback": null,
        "exception_message": null
      }
    }
  ],
  "suite_name": "customer_quality_suite_v1",
  "suite_parameters": {},
  "statistics": {
    "evaluated_expectations": 5,
    "successful_expectations": 5,
    "unsuccessful_expectations": 0,
    "success_percent": 100.0
  },
  "meta": {
    "great_expectations_version": "1.23.1",
    "batch_spec": {
      "batch_data": "PandasDataFrame"
    },
    "batch_markers": {
      "ge_load_time": "20260927T141338.202099Z",
      "pandas_data_fingerprint": "e96a4c39ff8f2a62253051bf70d34bca"
    },
    "active_batch_definition": {
      "datasource_name": "customer_data_source",
      "data_connector_name": "fluent",
      "data_asset_name": "customer",
      "batch_identifiers": {
        "dataframe": "<DATAFRAME>"
      }
    }
  },
  "id": null
}

In [ ]:
for expectation in suite.expectations:
    print(expectation)

id='602d8e76-98a7-4b33-9c58-3b821e1ac62d' meta=None notes=None result_format=<ResultFormat.BASIC: 'BASIC'> description=None catch_exceptions=True rendered_content=None severity=<FailureSeverity.CRITICAL: 'critical'> windows=None batch_id=None column='customer_id' mostly=1 row_condition=None condition_parser=None
id='cbf63011-d237-40f0-9607-614a456da495' meta=None notes=None result_format=<ResultFormat.BASIC: 'BASIC'> description=None catch_exceptions=True rendered_content=None severity=<FailureSeverity.CRITICAL: 'critical'> windows=None batch_id=None column='customer_id' mostly=1 row_condition=None condition_parser=None
id='dfab93aa-7b3d-46a0-8d72-a62f6ae2cdf6' meta=None notes=None result_format=<ResultFormat.BASIC: 'BASIC'> description=None catch_exceptions=True rendered_content=None severity=<FailureSeverity.CRITICAL: 'critical'> windows=None batch_id=None column='age' mostly=1 row_condition=None condition_parser=None min_value=18.0 max_value=100.0 strict_min=False strict_max=False
id='ae27598a-80b0-4062-a43c-aee3363fd43f' meta=None notes=None result_format=<ResultFormat.BASIC: 'BASIC'> description=None catch_exceptions=False rendered_content=None severity=<FailureSeverity.CRITICAL: 'critical'> windows=None batch_id=None column='status' row_condition=None condition_parser=None value_set=['active', 'inactive']
id='646bf99e-f1ca-4012-8491-eb4d507d9253' meta=None notes=None result_format=<ResultFormat.BASIC: 'BASIC'> description=None catch_exceptions=True rendered_content=None severity=<FailureSeverity.CRITICAL: 'critical'> windows=None batch_id=None column='email' mostly=1 row_condition=None condition_parser=None

In [ ]:
[x for x in dir(suite) if "expectation" in x.lower()]

['_add_expectation',
 '_build_expectation',
 '_expectations_are_equalish',
 '_find_expectation_indexes',
 '_process_expectation',
 '_save_expectation',
 'add_expectation',
 'add_expectation_configuration',
 'add_expectation_configurations',
 'delete_expectation',
 'expectation_configurations',
 'expectations',
 'remove_expectation']

In [ ]:
help(suite.delete_expectation)

Help on method delete_expectation in module great_expectations.core.expectation_suite:

delete_expectation(expectation: 'Expectation') -> 'Expectation' method of great_expectations.core.expectation_suite.ExpectationSuite instance
    --Public API--Delete an Expectation from the collection.

    Example:
        >>> suite.delete_expectation(suite.expectations[0])

    Raises:
        KeyError: Expectation not found in suite.

In [ ]:
for i, expectation in enumerate(suite.expectations):
    print(i, expectation)

0 id='602d8e76-98a7-4b33-9c58-3b821e1ac62d' meta=None notes=None result_format=<ResultFormat.BASIC: 'BASIC'> description=None catch_exceptions=True rendered_content=None severity=<FailureSeverity.CRITICAL: 'critical'> windows=None batch_id=None column='customer_id' mostly=1 row_condition=None condition_parser=None
1 id='cbf63011-d237-40f0-9607-614a456da495' meta=None notes=None result_format=<ResultFormat.BASIC: 'BASIC'> description=None catch_exceptions=True rendered_content=None severity=<FailureSeverity.CRITICAL: 'critical'> windows=None batch_id=None column='customer_id' mostly=1 row_condition=None condition_parser=None
2 id='dfab93aa-7b3d-46a0-8d72-a62f6ae2cdf6' meta=None notes=None result_format=<ResultFormat.BASIC: 'BASIC'> description=None catch_exceptions=True rendered_content=None severity=<FailureSeverity.CRITICAL: 'critical'> windows=None batch_id=None column='age' mostly=1 row_condition=None condition_parser=None min_value=18.0 max_value=100.0 strict_min=False strict_max=False
3 id='ae27598a-80b0-4062-a43c-aee3363fd43f' meta=None notes=None result_format=<ResultFormat.BASIC: 'BASIC'> description=None catch_exceptions=False rendered_content=None severity=<FailureSeverity.CRITICAL: 'critical'> windows=None batch_id=None column='status' row_condition=None condition_parser=None value_set=['active', 'inactive']
4 id='646bf99e-f1ca-4012-8491-eb4d507d9253' meta=None notes=None result_format=<ResultFormat.BASIC: 'BASIC'> description=None catch_exceptions=True rendered_content=None severity=<FailureSeverity.CRITICAL: 'critical'> windows=None batch_id=None column='email' mostly=1 row_condition=None condition_parser=None

In [ ]:
print(len(suite.expectations))

5

In [ ]:
validation_result = batch.validate(
    expect=suite
)

Calculating Metrics: 100%|██████████| 27/27 [00:00<00:00, 1091.53it/s]

In [ ]:
print(validation_result)

{
  "success": true,
  "results": [
    {
      "success": true,
      "expectation_config": {
        "type": "expect_column_values_to_not_be_null",
        "kwargs": {
          "batch_id": "customer_data_source-customer",
          "column": "customer_id"
        },
        "meta": {},
        "id": "602d8e76-98a7-4b33-9c58-3b821e1ac62d",
        "severity": "critical"
      },
      "result": {
        "element_count": 10,
        "unexpected_count": 0,
        "unexpected_percent": 0.0,
        "partial_unexpected_list": [],
        "partial_unexpected_counts": [],
        "partial_unexpected_index_list": []
      },
      "meta": {},
      "exception_info": {
        "raised_exception": false,
        "exception_traceback": null,
        "exception_message": null
      }
    },
    {
      "success": true,
      "expectation_config": {
        "type": "expect_column_values_to_be_unique",
        "kwargs": {
          "batch_id": "customer_data_source-customer",
          "column": "customer_id"
        },
        "meta": {},
        "id": "cbf63011-d237-40f0-9607-614a456da495",
        "severity": "critical"
      },
      "result": {
        "element_count": 10,
        "unexpected_count": 0,
        "unexpected_percent": 0.0,
        "partial_unexpected_list": [],
        "missing_count": 0,
        "missing_percent": 0.0,
        "unexpected_percent_total": 0.0,
        "unexpected_percent_nonmissing": 0.0,
        "partial_unexpected_counts": [],
        "partial_unexpected_index_list": []
      },
      "meta": {},
      "exception_info": {
        "raised_exception": false,
        "exception_traceback": null,
        "exception_message": null
      }
    },
    {
      "success": true,
      "expectation_config": {
        "type": "expect_column_values_to_be_between",
        "kwargs": {
          "batch_id": "customer_data_source-customer",
          "column": "age",
          "min_value": 18.0,
          "max_value": 100.0
        },
        "meta": {},
        "id": "dfab93aa-7b3d-46a0-8d72-a62f6ae2cdf6",
        "severity": "critical"
      },
      "result": {
        "element_count": 10,
        "unexpected_count": 0,
        "unexpected_percent": 0.0,
        "partial_unexpected_list": [],
        "missing_count": 0,
        "missing_percent": 0.0,
        "unexpected_percent_total": 0.0,
        "unexpected_percent_nonmissing": 0.0,
        "partial_unexpected_counts": [],
        "partial_unexpected_index_list": []
      },
      "meta": {},
      "exception_info": {
        "raised_exception": false,
        "exception_traceback": null,
        "exception_message": null
      }
    },
    {
      "success": true,
      "expectation_config": {
        "type": "expect_column_distinct_values_to_be_in_set",
        "kwargs": {
          "batch_id": "customer_data_source-customer",
          "column": "status",
          "value_set": [
            "active",
            "inactive"
          ]
        },
        "meta": {},
        "id": "ae27598a-80b0-4062-a43c-aee3363fd43f",
        "severity": "critical"
      },
      "result": {
        "observed_value": null,
        "unexpected_count": 0,
        "partial_unexpected_list": []
      },
      "meta": {},
      "exception_info": {
        "raised_exception": false,
        "exception_traceback": null,
        "exception_message": null
      }
    },
    {
      "success": true,
      "expectation_config": {
        "type": "expect_column_values_to_not_be_null",
        "kwargs": {
          "batch_id": "customer_data_source-customer",
          "column": "email"
        },
        "meta": {},
        "id": "646bf99e-f1ca-4012-8491-eb4d507d9253",
        "severity": "critical"
      },
      "result": {
        "element_count": 10,
        "unexpected_count": 0,
        "unexpected_percent": 0.0,
        "partial_unexpected_list": [],
        "partial_unexpected_counts": [],
        "partial_unexpected_index_list": []
      },
      "meta": {},
      "exception_info": {
        "raised_exception": false,
        "exception_traceback": null,
        "exception_message": null
      }
    }
  ],
  "suite_name": "customer_quality_suite_v1",
  "suite_parameters": {},
  "statistics": {
    "evaluated_expectations": 5,
    "successful_expectations": 5,
    "unsuccessful_expectations": 0,
    "success_percent": 100.0
  },
  "meta": {
    "great_expectations_version": "1.23.1",
    "batch_spec": {
      "batch_data": "PandasDataFrame"
    },
    "batch_markers": {
      "ge_load_time": "20260927T141338.418999Z",
      "pandas_data_fingerprint": "e96a4c39ff8f2a62253051bf70d34bca"
    },
    "active_batch_definition": {
      "datasource_name": "customer_data_source",
      "data_connector_name": "fluent",
      "data_asset_name": "customer",
      "batch_identifiers": {
        "dataframe": "<DATAFRAME>"
      }
    }
  },
  "id": null
}

to interpret wrong data

In [ ]:
bad_df = df.copy()

In [ ]:
bad_df.loc[1, "customer_id"] = bad_df.loc[0, "customer_id"]

In [ ]:
bad_df

  customer_id           name                email  age country    status
0        C001  Alice Johnson    alice@example.com   32   India    active
1        C001      Bob Smith      bob@example.com   45   India    active
2        C003  Charlie Brown  charlie@example.com   28     USA    active
3        C004   Diana Prince    diana@example.com   35      UK  inactive
4        C005     Ethan Hunt    ethan@example.com   41     USA    active
5        C006    Fiona Green    fiona@example.com   29   India    active
6        C007  George Miller   george@example.com   52  Canada    active
7        C008     Hannah Lee   hannah@example.com   24   India    active
8        C009     Ian Wright      ian@example.com   38      UK    active
9        C010    Julia Adams    julia@example.com   31     USA  inactive

In [ ]:
bad_batch = batch_definition.get_batch(
    batch_parameters={
        "dataframe": bad_df
    }
)

In [ ]:
bad_result = bad_batch.validate(
    expect=suite
)

Calculating Metrics: 100%|██████████| 27/27 [00:00<00:00, 879.09it/s]

In [ ]:
print(bad_result)

{
  "success": false,
  "results": [
    {
      "success": true,
      "expectation_config": {
        "type": "expect_column_values_to_not_be_null",
        "kwargs": {
          "batch_id": "customer_data_source-customer",
          "column": "customer_id"
        },
        "meta": {},
        "id": "602d8e76-98a7-4b33-9c58-3b821e1ac62d",
        "severity": "critical"
      },
      "result": {
        "element_count": 10,
        "unexpected_count": 0,
        "unexpected_percent": 0.0,
        "partial_unexpected_list": [],
        "partial_unexpected_counts": [],
        "partial_unexpected_index_list": []
      },
      "meta": {},
      "exception_info": {
        "raised_exception": false,
        "exception_traceback": null,
        "exception_message": null
      }
    },
    {
      "success": false,
      "expectation_config": {
        "type": "expect_column_values_to_be_unique",
        "kwargs": {
          "batch_id": "customer_data_source-customer",
          "column": "customer_id"
        },
        "meta": {},
        "id": "cbf63011-d237-40f0-9607-614a456da495",
        "severity": "critical"
      },
      "result": {
        "element_count": 10,
        "unexpected_count": 2,
        "unexpected_percent": 20.0,
        "partial_unexpected_list": [
          "C001",
          "C001"
        ],
        "missing_count": 0,
        "missing_percent": 0.0,
        "unexpected_percent_total": 20.0,
        "unexpected_percent_nonmissing": 20.0,
        "partial_unexpected_counts": [
          {
            "value": "C001",
            "count": 2
          }
        ],
        "partial_unexpected_index_list": [
          0,
          1
        ]
      },
      "meta": {},
      "exception_info": {
        "raised_exception": false,
        "exception_traceback": null,
        "exception_message": null
      }
    },
    {
      "success": true,
      "expectation_config": {
        "type": "expect_column_values_to_be_between",
        "kwargs": {
          "batch_id": "customer_data_source-customer",
          "column": "age",
          "min_value": 18.0,
          "max_value": 100.0
        },
        "meta": {},
        "id": "dfab93aa-7b3d-46a0-8d72-a62f6ae2cdf6",
        "severity": "critical"
      },
      "result": {
        "element_count": 10,
        "unexpected_count": 0,
        "unexpected_percent": 0.0,
        "partial_unexpected_list": [],
        "missing_count": 0,
        "missing_percent": 0.0,
        "unexpected_percent_total": 0.0,
        "unexpected_percent_nonmissing": 0.0,
        "partial_unexpected_counts": [],
        "partial_unexpected_index_list": []
      },
      "meta": {},
      "exception_info": {
        "raised_exception": false,
        "exception_traceback": null,
        "exception_message": null
      }
    },
    {
      "success": true,
      "expectation_config": {
        "type": "expect_column_distinct_values_to_be_in_set",
        "kwargs": {
          "batch_id": "customer_data_source-customer",
          "column": "status",
          "value_set": [
            "active",
            "inactive"
          ]
        },
        "meta": {},
        "id": "ae27598a-80b0-4062-a43c-aee3363fd43f",
        "severity": "critical"
      },
      "result": {
        "observed_value": null,
        "unexpected_count": 0,
        "partial_unexpected_list": []
      },
      "meta": {},
      "exception_info": {
        "raised_exception": false,
        "exception_traceback": null,
        "exception_message": null
      }
    },
    {
      "success": true,
      "expectation_config": {
        "type": "expect_column_values_to_not_be_null",
        "kwargs": {
          "batch_id": "customer_data_source-customer",
          "column": "email"
        },
        "meta": {},
        "id": "646bf99e-f1ca-4012-8491-eb4d507d9253",
        "severity": "critical"
      },
      "result": {
        "element_count": 10,
        "unexpected_count": 0,
        "unexpected_percent": 0.0,
        "partial_unexpected_list": [],
        "partial_unexpected_counts": [],
        "partial_unexpected_index_list": []
      },
      "meta": {},
      "exception_info": {
        "raised_exception": false,
        "exception_traceback": null,
        "exception_message": null
      }
    }
  ],
  "suite_name": "customer_quality_suite_v1",
  "suite_parameters": {},
  "statistics": {
    "evaluated_expectations": 5,
    "successful_expectations": 4,
    "unsuccessful_expectations": 1,
    "success_percent": 80.0
  },
  "meta": {
    "great_expectations_version": "1.23.1",
    "batch_spec": {
      "batch_data": "PandasDataFrame"
    },
    "batch_markers": {
      "ge_load_time": "20260927T141338.619194Z",
      "pandas_data_fingerprint": "568bff6830f4cfafc2c52d715962b17b"
    },
    "active_batch_definition": {
      "datasource_name": "customer_data_source",
      "data_connector_name": "fluent",
      "data_asset_name": "customer",
      "batch_identifiers": {
        "dataframe": "<DATAFRAME>"
      }
    }
  },
  "id": null
}

In [ ]:
bad_df2 = df.copy()
bad_df2.loc[1, "customer_id"] = bad_df2.loc[0, "customer_id"]
bad_df2.loc[2, "status"] = "pending"

In [ ]:
bad_batch2 = batch_definition.get_batch(
    batch_parameters={
        "dataframe": bad_df2
    }
)

In [ ]:
bad_result2 = bad_batch2.validate(
    expect=suite
)

Calculating Metrics: 100%|██████████| 27/27 [00:00<00:00, 941.84it/s]

In [ ]:
print(bad_result2)

{
  "success": false,
  "results": [
    {
      "success": true,
      "expectation_config": {
        "type": "expect_column_values_to_not_be_null",
        "kwargs": {
          "batch_id": "customer_data_source-customer",
          "column": "customer_id"
        },
        "meta": {},
        "id": "602d8e76-98a7-4b33-9c58-3b821e1ac62d",
        "severity": "critical"
      },
      "result": {
        "element_count": 10,
        "unexpected_count": 0,
        "unexpected_percent": 0.0,
        "partial_unexpected_list": [],
        "partial_unexpected_counts": [],
        "partial_unexpected_index_list": []
      },
      "meta": {},
      "exception_info": {
        "raised_exception": false,
        "exception_traceback": null,
        "exception_message": null
      }
    },
    {
      "success": false,
      "expectation_config": {
        "type": "expect_column_values_to_be_unique",
        "kwargs": {
          "batch_id": "customer_data_source-customer",
          "column": "customer_id"
        },
        "meta": {},
        "id": "cbf63011-d237-40f0-9607-614a456da495",
        "severity": "critical"
      },
      "result": {
        "element_count": 10,
        "unexpected_count": 2,
        "unexpected_percent": 20.0,
        "partial_unexpected_list": [
          "C001",
          "C001"
        ],
        "missing_count": 0,
        "missing_percent": 0.0,
        "unexpected_percent_total": 20.0,
        "unexpected_percent_nonmissing": 20.0,
        "partial_unexpected_counts": [
          {
            "value": "C001",
            "count": 2
          }
        ],
        "partial_unexpected_index_list": [
          0,
          1
        ]
      },
      "meta": {},
      "exception_info": {
        "raised_exception": false,
        "exception_traceback": null,
        "exception_message": null
      }
    },
    {
      "success": true,
      "expectation_config": {
        "type": "expect_column_values_to_be_between",
        "kwargs": {
          "batch_id": "customer_data_source-customer",
          "column": "age",
          "min_value": 18.0,
          "max_value": 100.0
        },
        "meta": {},
        "id": "dfab93aa-7b3d-46a0-8d72-a62f6ae2cdf6",
        "severity": "critical"
      },
      "result": {
        "element_count": 10,
        "unexpected_count": 0,
        "unexpected_percent": 0.0,
        "partial_unexpected_list": [],
        "missing_count": 0,
        "missing_percent": 0.0,
        "unexpected_percent_total": 0.0,
        "unexpected_percent_nonmissing": 0.0,
        "partial_unexpected_counts": [],
        "partial_unexpected_index_list": []
      },
      "meta": {},
      "exception_info": {
        "raised_exception": false,
        "exception_traceback": null,
        "exception_message": null
      }
    },
    {
      "success": false,
      "expectation_config": {
        "type": "expect_column_distinct_values_to_be_in_set",
        "kwargs": {
          "batch_id": "customer_data_source-customer",
          "column": "status",
          "value_set": [
            "active",
            "inactive"
          ]
        },
        "meta": {},
        "id": "ae27598a-80b0-4062-a43c-aee3363fd43f",
        "severity": "critical"
      },
      "result": {
        "observed_value": null,
        "unexpected_count": 1,
        "partial_unexpected_list": [
          "pending"
        ]
      },
      "meta": {},
      "exception_info": {
        "raised_exception": false,
        "exception_traceback": null,
        "exception_message": null
      }
    },
    {
      "success": true,
      "expectation_config": {
        "type": "expect_column_values_to_not_be_null",
        "kwargs": {
          "batch_id": "customer_data_source-customer",
          "column": "email"
        },
        "meta": {},
        "id": "646bf99e-f1ca-4012-8491-eb4d507d9253",
        "severity": "critical"
      },
      "result": {
        "element_count": 10,
        "unexpected_count": 0,
        "unexpected_percent": 0.0,
        "partial_unexpected_list": [],
        "partial_unexpected_counts": [],
        "partial_unexpected_index_list": []
      },
      "meta": {},
      "exception_info": {
        "raised_exception": false,
        "exception_traceback": null,
        "exception_message": null
      }
    }
  ],
  "suite_name": "customer_quality_suite_v1",
  "suite_parameters": {},
  "statistics": {
    "evaluated_expectations": 5,
    "successful_expectations": 3,
    "unsuccessful_expectations": 2,
    "success_percent": 60.0
  },
  "meta": {
    "great_expectations_version": "1.23.1",
    "batch_spec": {
      "batch_data": "PandasDataFrame"
    },
    "batch_markers": {
      "ge_load_time": "20260927T141338.786005Z",
      "pandas_data_fingerprint": "33ac47bb3a15874ba0b3adb1d3ac5f24"
    },
    "active_batch_definition": {
      "datasource_name": "customer_data_source",
      "data_connector_name": "fluent",
      "data_asset_name": "customer",
      "batch_identifiers": {
        "dataframe": "<DATAFRAME>"
      }
    }
  },
  "id": null
}

In [ ]:
#email 
[x for x in dir(gx.expectations) if "Match" in x or "Regex" in x]

['ExpectColumnValuesToMatchJsonSchema',
 'ExpectColumnValuesToMatchLikePattern',
 'ExpectColumnValuesToMatchLikePatternList',
 'ExpectColumnValuesToMatchRegex',
 'ExpectColumnValuesToMatchRegexList',
 'ExpectColumnValuesToMatchStrftimeFormat',
 'ExpectColumnValuesToNotMatchLikePattern',
 'ExpectColumnValuesToNotMatchLikePatternList',
 'ExpectColumnValuesToNotMatchRegex',
 'ExpectColumnValuesToNotMatchRegexList',
 'ExpectQueryResultsToMatchComparison',
 'ExpectTableColumnsToMatchOrderedList',
 'ExpectTableColumnsToMatchSet']

In [ ]:
help(gx.expectations.ExpectColumnValuesToMatchRegex)

Help on class ExpectColumnValuesToMatchRegex in module great_expectations.expectations.core.expect_column_values_to_match_regex:

class ExpectColumnValuesToMatchRegex(great_expectations.expectations.expectation.ColumnMapExpectation)
 |  ExpectColumnValuesToMatchRegex(
 |      *,
 |      id: Optional[str] = None,
 |      meta: Optional[dict] = None,
 |      notes: Union[str, List[str], NoneType] = None,
 |      result_format: Union[great_expectations.core.result_format.ResultFormat, dict] = <ResultFormat.BASIC: 'BASIC'>,
 |      description: Optional[str] = None,
 |      catch_exceptions: bool = True,
 |      rendered_content: Optional[List[great_expectations.render.components.RenderedAtomicContent]] = None,
 |      severity: great_expectations.expectations.metadata_types.FailureSeverity = <FailureSeverity.CRITICAL: 'critical'>,
 |      windows: Optional[List[great_expectations.expectations.window.Window]] = None,
 |      batch_id: Optional[str] = None,
 |      column: pydantic.v1.schema.StrictStr,
 |      mostly: Union[pydantic.v1.types.ConstrainedFloatValue, dict] = 1,
 |      row_condition: Union[str, great_expectations.expectations.row_conditions.ComparisonCondition, great_expectations.expectations.row_conditions.NullityCondition, great_expectations.expectations.row_conditions.AndCondition, great_expectations.expectations.row_conditions.OrCondition, great_expectations.expectations.row_conditions.PassThroughCondition, NoneType] = None,
 |      condition_parser: Optional[Literal['great_expectations', 'great_expectations__experimental__', 'pandas', 'spark']] = None,
 |      regex: Union[str, dict] = '(?s).*'
 |  ) -> None
 |
 |  Expect the column entries to be strings that match a given regular expression.
 |
 |  Valid matches can be found     anywhere in the string, for example "[at]+" will identify the following strings as expected: "cat", "hat",     "aa", "a", and "t", and the following strings as unexpected: "fish", "dog".
 |
 |  ExpectColumnValuesToMatchRegex is a     Column Map Expectation.
 |
 |  Column Map Expectations are one of the most common types of Expectation.
 |  They are evaluated for a single column and ask a yes/no question for every row in that column.
 |  Based on the result, they then calculate the percentage of rows that gave a positive answer. If the percentage is high enough, the Expectation considers that data valid.
 |
 |  Args:
 |      column (str):             The column name.
 |      regex (str):             The regular expression the column entries should match.
 |
 |  Other Parameters:
 |      mostly (None or a float between 0 and 1):             Successful if at least `mostly` fraction of values match the Expectation.             For more detail, see [mostly](https://docs.greatexpectations.io/docs/reference/expectations/standard_arguments/#mostly). Default 1.
 |      result_format (str or None):             Which output mode to use: BOOLEAN_ONLY, BASIC, COMPLETE, or SUMMARY.             For more detail, see [result_format](https://docs.greatexpectations.io/docs/reference/expectations/result_format).
 |      catch_exceptions (boolean or None):             If True, then catch exceptions and include them as part of the result object.             For more detail, see [catch_exceptions](https://docs.greatexpectations.io/docs/reference/expectations/standard_arguments/#catch_exceptions).
 |      meta (dict or None):             A JSON-serializable dictionary (nesting allowed) that will be included in the output without             modification. For more detail, see [meta](https://docs.greatexpectations.io/docs/reference/expectations/standard_arguments/#meta).
 |      severity (str or None):             The impact of this Expectation failing: critical, warning, or info. Defaults to critical if not set. Severity levels can be used to trigger different alerting patterns and actions.             For more detail, see [failure severity](https://docs.greatexpectations.io/docs/cloud/expectations/expectations_overview/#failure-severity).
 |
 |  Returns:
 |      An [ExpectationSuiteValidationResult](https://docs.greatexpectations.io/docs/terms/validation_result)
 |
 |      Exact fields vary depending on the values passed to result_format, catch_exceptions, and meta.
 |
 |  See Also:
 |      [ExpectColumnValuesToMatchRegexList](https://greatexpectations.io/expectations/expect_column_values_to_match_regex_list)
 |      [ExpectColumnValuesToNotMatchRegex](https://greatexpectations.io/expectations/expect_column_values_to_not_match_regex)
 |      [ExpectColumnValuesToNotMatchRegexList](https://greatexpectations.io/expectations/expect_column_values_to_not_match_regex_list)
 |      [ExpectColumnValuesToMatchLikePattern](https://greatexpectations.io/expectations/expect_column_values_to_match_like_pattern)
 |      [ExpectColumnValuesToMatchLikePatternList](https://greatexpectations.io/expectations/expect_column_values_to_match_like_pattern_list)
 |      [ExpectColumnValuesToNotMatchLikePattern](https://greatexpectations.io/expectations/expect_column_values_to_not_match_like_pattern)
 |      [ExpectColumnValuesToNotMatchLikePatternList](https://greatexpectations.io/expectations/expect_column_values_to_not_match_like_pattern_list)
 |
 |  Supported Data Sources:
 |      [Pandas](https://docs.greatexpectations.io/docs/application_integration_support/)
 |      [Spark](https://docs.greatexpectations.io/docs/application_integration_support/)
 |      [SQLite](https://docs.greatexpectations.io/docs/application_integration_support/)
 |      [PostgreSQL](https://docs.greatexpectations.io/docs/application_integration_support/)
 |      [Amazon Aurora PostgreSQL](https://docs.greatexpectations.io/docs/application_integration_support/)
 |      [Citus](https://docs.greatexpectations.io/docs/application_integration_support/)
 |      [AlloyDB](https://docs.greatexpectations.io/docs/application_integration_support/)
 |      [Neon](https://docs.greatexpectations.io/docs/application_integration_support/)
 |      [MySQL](https://docs.greatexpectations.io/docs/application_integration_support/)
 |      [BigQuery](https://docs.greatexpectations.io/docs/application_integration_support/)
 |      [Databricks (SQL)](https://docs.greatexpectations.io/docs/application_integration_support/)
 |  Data Quality Issues:
 |      Validity
 |
 |  Example Data:
 |              test    test2
 |          0   "aaa"   "bcc"
 |          1   "abb"   "bdd"
 |          2   "acc"   "abc"
 |
 |  Code Examples:
 |      Passing Case:
 |          Input:
 |              ExpectColumnValuesToMatchRegex(
 |                  column="test",
 |                  regex="^a.*",
 |          )
 |
 |          Output:
 |              {
 |                "exception_info": {
 |                  "raised_exception": false,
 |                  "exception_traceback": null,
 |                  "exception_message": null
 |                },
 |                "result": {
 |                  "element_count": 3,
 |                  "unexpected_count": 0,
 |                  "unexpected_percent": 0.0,
 |                  "partial_unexpected_list": [],
 |                  "missing_count": 0,
 |                  "missing_percent": 0.0,
 |                  "unexpected_percent_total": 0.0,
 |                  "unexpected_percent_nonmissing": 0.0
 |                },
 |                "meta": {},
 |                "success": true
 |              }
 |
 |      Failing Case:
 |          Input:
 |              ExpectColumnValuesToMatchRegex(
 |                  column="test2",
 |                  regex="^a.*",
 |          )
 |
 |          Output:
 |              {
 |                "exception_info": {
 |                  "raised_exception": false,
 |                  "exception_traceback": null,
 |                  "exception_message": null
 |                },
 |                "result": {
 |                  "element_count": 3,
 |                  "unexpected_count": 2,
 |                  "unexpected_percent": 66.66666666666666,
 |                  "partial_unexpected_list": [
 |                    "bcc",
 |                    "bdd"
 |                  ],
 |                  "missing_count": 0,
 |                  "missing_percent": 0.0,
 |                  "unexpected_percent_total": 66.66666666666666,
 |                  "unexpected_percent_nonmissing": 66.66666666666666
 |                },
 |                "meta": {},
 |                "success": false
 |              }
 |
 |  Method resolution order:
 |      ExpectColumnValuesToMatchRegex
 |      great_expectations.expectations.expectation.ColumnMapExpectation
 |      great_expectations.expectations.expectation.BatchExpectation
 |      great_expectations.expectations.expectation.Expectation
 |      pydantic.v1.main.BaseModel
 |      pydantic.v1.utils.Representation
 |      abc.ABC
 |      builtins.object
 |
 |  Methods defined here:
 |
 |  __hash__(self) -> 'int' from great_expectations.expectations.expectation.Expectation
 |      Return hash(self).
 |
 |  ----------------------------------------------------------------------
 |  Static methods defined here:
 |
 |  __json_encoder__ = functools.partial(<function custom_pydantic_enco...ectation.Config.<lambda> at 0x000001FEAECAEE80>})
 |  ----------------------------------------------------------------------
 |  Data and other attributes defined here:
 |
 |  Config = <class 'great_expectations.expectations.core.exp...tch_regex....
 |
 |  __abstractmethods__ = frozenset()
 |
 |  __annotations__ = {'library_metadata': 'ClassVar[Dict[str, Union[str, ...
 |
 |  __class_vars__ = {'args_keys', 'domain_keys', 'domain_type', 'examples...
 |
 |  __config__ = <class 'pydantic.v1.config.Config'>
 |
 |  __custom_root_type__ = False
 |
 |  __exclude_fields__ = None
 |
 |  __fields__ = {'batch_id': ModelField(name='batch_id', type=Optional[st...
 |
 |  __include_fields__ = None
 |
 |  __post_root_validators__ = [(False, <function Expectation._transform_l...
 |
 |  __pre_root_validators__ = []
 |
 |  __private_attributes__ = {'_save_callback': ModelPrivateAttr()}
 |
 |  __schema_cache__ = {}
 |
 |  __signature__ = <Signature (*, id: Optional[str] = None, meta: O...one...
 |
 |  __validators__ = {'result_format': [<pydantic.v1.class_validators.Vali...
 |
 |  args_keys = ('column', 'regex')
 |
 |  expectation_type = 'expect_column_values_to_match_regex'
 |
 |  library_metadata = {'contributors': ['@great_expectations'], 'has_full...
 |
 |  map_metric = 'column_values.match_regex'
 |
 |  success_keys = ('regex', 'mostly')
 |
 |  ----------------------------------------------------------------------
 |  Methods inherited from great_expectations.expectations.expectation.ColumnMapExpectation:
 |
 |  get_validation_dependencies(
 |      self,
 |      execution_engine: 'Optional[ExecutionEngine]' = None,
 |      runtime_configuration: 'Optional[dict]' = None,
 |      **kwargs: 'dict'
 |  ) -> 'ValidationDependencies'
 |      Returns the result format and metrics required to validate this Expectation using the provided result format.
 |
 |  ----------------------------------------------------------------------
 |  Class methods inherited from great_expectations.expectations.expectation.ColumnMapExpectation:
 |
 |  is_abstract() -> 'bool'
 |
 |  ----------------------------------------------------------------------
 |  Data and other attributes inherited from great_expectations.expectations.expectation.ColumnMapExpectation:
 |
 |  domain_keys = ('batch_id', 'column', 'row_condition', 'condition_parse...
 |
 |  domain_type = <MetricDomainTypes.COLUMN: 'column'>
 |
 |  ----------------------------------------------------------------------
 |  Data and other attributes inherited from great_expectations.expectations.expectation.BatchExpectation:
 |
 |  metric_dependencies = ()
 |
 |  ----------------------------------------------------------------------
 |  Methods inherited from great_expectations.expectations.expectation.Expectation:
 |
 |  __copy__(self)
 |
 |  __eq__(self, other: 'object') -> 'bool'
 |      Return self==value.
 |
 |  __lt__(self, other: 'object') -> 'bool'
 |      Return self<value.
 |
 |  metrics_validate(
 |      self,
 |      metrics: 'dict',
 |      runtime_configuration: 'Optional[dict]' = None,
 |      execution_engine: 'Optional[ExecutionEngine]' = None,
 |      **kwargs: 'dict'
 |  ) -> 'ExpectationValidationResult'
 |      # noinspection PyUnusedLocal
 |
 |  print_diagnostic_checklist(
 |      self,
 |      diagnostics: 'Optional[ExpectationDiagnostics]' = None,
 |      show_failed_tests: 'bool' = False,
 |      backends: 'Optional[List[str]]' = None,
 |      show_debug_messages: 'bool' = False
 |  ) -> 'str'
 |      --Public API--Runs self.run_diagnostics and generates a diagnostic checklist.
 |
 |      This output from this method is a thin wrapper for ExpectationDiagnostics.generate_checklist()
 |      This method is experimental.
 |
 |      Args:
 |          diagnostics (optional[ExpectationDiagnostics]): If diagnostics are not provided, diagnostics will be ran on self.
 |          show_failed_tests (bool): If true, failing tests will be printed.
 |          backends: list of backends to pass to run_diagnostics
 |          show_debug_messages (bool): If true, create a logger and pass to run_diagnostics
 |
 |  register_save_callback(
 |      self,
 |      save_callback: 'Callable[[Expectation], Expectation]'
 |  ) -> 'None'
 |
 |  render(self) -> 'None'
 |      Renders content using the atomic prescriptive renderer for each expectation configuration associated with
 |         this ExpectationSuite to ExpectationConfiguration.rendered_content.
 |
 |  run_diagnostics(
 |      self,
 |      raise_exceptions_for_backends: 'bool' = False,
 |      ignore_suppress: 'bool' = False,
 |      ignore_only_for: 'bool' = False,
 |      for_gallery: 'bool' = False,
 |      debug_logger: 'Optional[logging.Logger]' = None,
 |      only_consider_these_backends: 'Optional[List[str]]' = None,
 |      context: 'Optional[AbstractDataContext]' = None
 |  ) -> 'ExpectationDiagnostics'
 |      --Public API--Produce a diagnostic report about this Expectation.
 |
 |      The current uses for this method's output are
 |      using the JSON structure to populate the Public Expectation Gallery
 |      and enabling a fast dev loop for developing new Expectations where the
 |      contributors can quickly check the completeness of their expectations.
 |
 |      The contents of the report are captured in the ExpectationDiagnostics dataclass.
 |      You can see some examples in test_expectation_diagnostics.py
 |
 |      Some components (e.g. description, examples, library_metadata) of the diagnostic report can be introspected directly from the Exepctation class.
 |      Other components (e.g. metrics, renderers, executions) are at least partly dependent on instantiating, validating, and/or executing the Expectation class.
 |      For these kinds of components, at least one test case with include_in_gallery=True must be present in the examples to
 |      produce the metrics, renderers and execution engines parts of the report. This is due to
 |      a get_validation_dependencies requiring expectation_config as an argument.
 |
 |      If errors are encountered in the process of running the diagnostics, they are assumed to be due to
 |      incompleteness of the Expectation's implementation (e.g., declaring a dependency on Metrics
 |      that do not exist). These errors are added under "errors" key in the report.
 |
 |      Args:
 |          raise_exceptions_for_backends: Bool object that when True will raise an Exception if a backend fails to connect.
 |          ignore_suppress:  Bool object that when True will ignore the suppress_test_for list on Expectation sample tests.
 |          ignore_only_for:  Bool object that when True will ignore the only_for list on Expectation sample tests.
 |          for_gallery:  Bool object that when True will create empty arrays to use as examples for the Expectation Diagnostics.
 |          debug_logger (optional[logging.Logger]):  Logger object to use for sending debug messages to.
 |          only_consider_these_backends (optional[List[str]])  List of backends to consider.
 |          context (optional[AbstractDataContext]): Instance of any child of "AbstractDataContext" class.
 |
 |      Returns:
 |          An Expectation Diagnostics report object
 |
 |  save(self)
 |      --Public API--Save the current state of this Expectation.
 |
 |  validate_(
 |      self,
 |      validator: 'Validator',
 |      suite_parameters: 'Optional[dict]' = None,
 |      interactive_evaluation: 'bool' = True,
 |      data_context: 'Optional[AbstractDataContext]' = None,
 |      runtime_configuration: 'Optional[dict]' = None
 |  ) -> 'ExpectationValidationResult'
 |      Validates the expectation against the provided data.
 |
 |      Args:
 |          validator: A Validator object that can be used to create Expectations, validate Expectations,
 |              and get Metrics for Expectations.
 |          suite_parameters: Dictionary of dynamic values used during Validation of an Expectation.
 |          interactive_evaluation: Setting the interactive_evaluation flag on a DataAsset
 |              make it possible to declare expectations and store expectations without
 |              immediately evaluating them.
 |          data_context: An instance of a GX DataContext.
 |          runtime_configuration: The runtime configuration for the Expectation.
 |      Returns:
 |          An ExpectationValidationResult object
 |
 |  validate_configuration(
 |      self,
 |      configuration: 'Optional[ExpectationConfiguration]' = None
 |  ) -> 'None'
 |
 |  ----------------------------------------------------------------------
 |  Class methods inherited from great_expectations.expectations.expectation.Expectation:
 |
 |  get_allowed_config_keys() -> 'Union[Tuple[str, ...], Tuple[str]]'
 |
 |  ----------------------------------------------------------------------
 |  Readonly properties inherited from great_expectations.expectations.expectation.Expectation:
 |
 |  configuration
 |
 |  suite_parameter_options
 |      SuiteParameter options for this Expectation.
 |
 |      Returns:
 |          tuple[str, ...]: The keys of the suite parameters used in this Expectation at runtime.
 |
 |  ----------------------------------------------------------------------
 |  Data and other attributes inherited from great_expectations.expectations.expectation.Expectation:
 |
 |  examples = []
 |
 |  runtime_keys = ('catch_exceptions', 'result_format')
 |
 |  version = '1.23.1'
 |
 |  ----------------------------------------------------------------------
 |  Methods inherited from pydantic.v1.main.BaseModel:
 |
 |  __getstate__(self) -> 'DictAny'
 |      Helper for pickle.
 |
 |  __init__(__pydantic_self__, **data: Any) -> None
 |      Create a new model by parsing and validating input data from keyword arguments.
 |
 |      Raises ValidationError if the input data cannot be parsed to form a valid model.
 |
 |  __iter__(self) -> 'TupleGenerator'
 |      so `dict(model)` works
 |
 |  __repr_args__(self) -> 'ReprArgs'
 |      Returns the attributes to show in __str__, __repr__, and __pretty__ this is generally overridden.
 |
 |      Can either return:
 |      * name - value pairs, e.g.: `[('foo_name', 'foo'), ('bar_name', ['b', 'a', 'r'])]`
 |      * or, just values, e.g.: `[(None, 'foo'), (None, ['b', 'a', 'r'])]`
 |
 |  __setattr__(self, name, value)
 |      Implement setattr(self, name, value).
 |
 |  __setstate__(self, state: 'DictAny') -> None
 |
 |  copy(
 |      self: 'Model',
 |      *,
 |      include: Union[ForwardRef('AbstractSetIntStr'), ForwardRef('MappingIntStrAny'), NoneType] = None,
 |      exclude: Union[ForwardRef('AbstractSetIntStr'), ForwardRef('MappingIntStrAny'), NoneType] = None,
 |      update: Optional[ForwardRef('DictStrAny')] = None,
 |      deep: bool = False
 |  ) -> 'Model'

In [ ]:
email_regex = gx.expectations.ExpectColumnValuesToMatchRegex(
    column = 'email',
    regex = r"^[^@\s]+@[^@\s]+\.[^@\s]+$"

)

In [ ]:
print(email_regex)

id=None meta=None notes=None result_format=<ResultFormat.BASIC: 'BASIC'> description=None catch_exceptions=True rendered_content=None severity=<FailureSeverity.CRITICAL: 'critical'> windows=None batch_id=None column='email' mostly=1 row_condition=None condition_parser=None regex='^[^@\\s]+@[^@\\s]+\\.[^@\\s]+$'

In [ ]:
suite.add_expectation(email_regex)

ExpectColumnValuesToMatchRegex(id='cc80d875-772e-4d1f-b209-f026c6a3b85f', meta=None, notes=None, result_format=<ResultFormat.BASIC: 'BASIC'>, description=None, catch_exceptions=True, rendered_content=None, severity=<FailureSeverity.CRITICAL: 'critical'>, windows=None, batch_id=None, column='email', mostly=1, row_condition=None, condition_parser=None, regex='^[^@\\s]+@[^@\\s]+\\.[^@\\s]+$')

In [ ]:
email_batch = batch_definition.get_batch(
    batch_parameters= {
        'dataframe': bad_df2
    }

)

In [ ]:
results = email_batch.validate(
    expect = suite
)

Calculating Metrics: 100%|██████████| 32/32 [00:00<00:00, 1052.00it/s]

In [ ]:
print(results)

{
  "success": false,
  "results": [
    {
      "success": true,
      "expectation_config": {
        "type": "expect_column_values_to_not_be_null",
        "kwargs": {
          "batch_id": "customer_data_source-customer",
          "column": "customer_id"
        },
        "meta": {},
        "id": "602d8e76-98a7-4b33-9c58-3b821e1ac62d",
        "severity": "critical"
      },
      "result": {
        "element_count": 10,
        "unexpected_count": 0,
        "unexpected_percent": 0.0,
        "partial_unexpected_list": [],
        "partial_unexpected_counts": [],
        "partial_unexpected_index_list": []
      },
      "meta": {},
      "exception_info": {
        "raised_exception": false,
        "exception_traceback": null,
        "exception_message": null
      }
    },
    {
      "success": false,
      "expectation_config": {
        "type": "expect_column_values_to_be_unique",
        "kwargs": {
          "batch_id": "customer_data_source-customer",
          "column": "customer_id"
        },
        "meta": {},
        "id": "cbf63011-d237-40f0-9607-614a456da495",
        "severity": "critical"
      },
      "result": {
        "element_count": 10,
        "unexpected_count": 2,
        "unexpected_percent": 20.0,
        "partial_unexpected_list": [
          "C001",
          "C001"
        ],
        "missing_count": 0,
        "missing_percent": 0.0,
        "unexpected_percent_total": 20.0,
        "unexpected_percent_nonmissing": 20.0,
        "partial_unexpected_counts": [
          {
            "value": "C001",
            "count": 2
          }
        ],
        "partial_unexpected_index_list": [
          0,
          1
        ]
      },
      "meta": {},
      "exception_info": {
        "raised_exception": false,
        "exception_traceback": null,
        "exception_message": null
      }
    },
    {
      "success": true,
      "expectation_config": {
        "type": "expect_column_values_to_be_between",
        "kwargs": {
          "batch_id": "customer_data_source-customer",
          "column": "age",
          "min_value": 18.0,
          "max_value": 100.0
        },
        "meta": {},
        "id": "dfab93aa-7b3d-46a0-8d72-a62f6ae2cdf6",
        "severity": "critical"
      },
      "result": {
        "element_count": 10,
        "unexpected_count": 0,
        "unexpected_percent": 0.0,
        "partial_unexpected_list": [],
        "missing_count": 0,
        "missing_percent": 0.0,
        "unexpected_percent_total": 0.0,
        "unexpected_percent_nonmissing": 0.0,
        "partial_unexpected_counts": [],
        "partial_unexpected_index_list": []
      },
      "meta": {},
      "exception_info": {
        "raised_exception": false,
        "exception_traceback": null,
        "exception_message": null
      }
    },
    {
      "success": false,
      "expectation_config": {
        "type": "expect_column_distinct_values_to_be_in_set",
        "kwargs": {
          "batch_id": "customer_data_source-customer",
          "column": "status",
          "value_set": [
            "active",
            "inactive"
          ]
        },
        "meta": {},
        "id": "ae27598a-80b0-4062-a43c-aee3363fd43f",
        "severity": "critical"
      },
      "result": {
        "observed_value": null,
        "unexpected_count": 1,
        "partial_unexpected_list": [
          "pending"
        ]
      },
      "meta": {},
      "exception_info": {
        "raised_exception": false,
        "exception_traceback": null,
        "exception_message": null
      }
    },
    {
      "success": true,
      "expectation_config": {
        "type": "expect_column_values_to_not_be_null",
        "kwargs": {
          "batch_id": "customer_data_source-customer",
          "column": "email"
        },
        "meta": {},
        "id": "646bf99e-f1ca-4012-8491-eb4d507d9253",
        "severity": "critical"
      },
      "result": {
        "element_count": 10,
        "unexpected_count": 0,
        "unexpected_percent": 0.0,
        "partial_unexpected_list": [],
        "partial_unexpected_counts": [],
        "partial_unexpected_index_list": []
      },
      "meta": {},
      "exception_info": {
        "raised_exception": false,
        "exception_traceback": null,
        "exception_message": null
      }
    },
    {
      "success": true,
      "expectation_config": {
        "type": "expect_column_values_to_match_regex",
        "kwargs": {
          "batch_id": "customer_data_source-customer",
          "column": "email",
          "regex": "^[^@\\s]+@[^@\\s]+\\.[^@\\s]+$"
        },
        "meta": {},
        "id": "cc80d875-772e-4d1f-b209-f026c6a3b85f",
        "severity": "critical"
      },
      "result": {
        "element_count": 10,
        "unexpected_count": 0,
        "unexpected_percent": 0.0,
        "partial_unexpected_list": [],
        "missing_count": 0,
        "missing_percent": 0.0,
        "unexpected_percent_total": 0.0,
        "unexpected_percent_nonmissing": 0.0,
        "partial_unexpected_counts": [],
        "partial_unexpected_index_list": []
      },
      "meta": {},
      "exception_info": {
        "raised_exception": false,
        "exception_traceback": null,
        "exception_message": null
      }
    }
  ],
  "suite_name": "customer_quality_suite_v1",
  "suite_parameters": {},
  "statistics": {
    "evaluated_expectations": 6,
    "successful_expectations": 4,
    "unsuccessful_expectations": 2,
    "success_percent": 66.66666666666666
  },
  "meta": {
    "great_expectations_version": "1.23.1",
    "batch_spec": {
      "batch_data": "PandasDataFrame"
    },
    "batch_markers": {
      "ge_load_time": "20260927T141339.021309Z",
      "pandas_data_fingerprint": "33ac47bb3a15874ba0b3adb1d3ac5f24"
    },
    "active_batch_definition": {
      "datasource_name": "customer_data_source",
      "data_connector_name": "fluent",
      "data_asset_name": "customer",
      "batch_identifiers": {
        "dataframe": "<DATAFRAME>"
      }
    }
  },
  "id": null
}

In [ ]:
bad_email_df = df.copy()

In [ ]:
bad_email_df.loc[3,'email'] = 'not-an-email'

In [ ]:
bad_email_batch = batch_definition.get_batch(
    batch_parameters = {
        'dataframe':bad_email_df
    }
)

In [ ]:
bad_email_results = bad_email_batch.validate(
    expect = suite
)

Calculating Metrics: 100%|██████████| 32/32 [00:00<00:00, 883.36it/s]

In [ ]:
print(bad_email_results)

{
  "success": false,
  "results": [
    {
      "success": true,
      "expectation_config": {
        "type": "expect_column_values_to_not_be_null",
        "kwargs": {
          "batch_id": "customer_data_source-customer",
          "column": "customer_id"
        },
        "meta": {},
        "id": "602d8e76-98a7-4b33-9c58-3b821e1ac62d",
        "severity": "critical"
      },
      "result": {
        "element_count": 10,
        "unexpected_count": 0,
        "unexpected_percent": 0.0,
        "partial_unexpected_list": [],
        "partial_unexpected_counts": [],
        "partial_unexpected_index_list": []
      },
      "meta": {},
      "exception_info": {
        "raised_exception": false,
        "exception_traceback": null,
        "exception_message": null
      }
    },
    {
      "success": true,
      "expectation_config": {
        "type": "expect_column_values_to_be_unique",
        "kwargs": {
          "batch_id": "customer_data_source-customer",
          "column": "customer_id"
        },
        "meta": {},
        "id": "cbf63011-d237-40f0-9607-614a456da495",
        "severity": "critical"
      },
      "result": {
        "element_count": 10,
        "unexpected_count": 0,
        "unexpected_percent": 0.0,
        "partial_unexpected_list": [],
        "missing_count": 0,
        "missing_percent": 0.0,
        "unexpected_percent_total": 0.0,
        "unexpected_percent_nonmissing": 0.0,
        "partial_unexpected_counts": [],
        "partial_unexpected_index_list": []
      },
      "meta": {},
      "exception_info": {
        "raised_exception": false,
        "exception_traceback": null,
        "exception_message": null
      }
    },
    {
      "success": true,
      "expectation_config": {
        "type": "expect_column_values_to_be_between",
        "kwargs": {
          "batch_id": "customer_data_source-customer",
          "column": "age",
          "min_value": 18.0,
          "max_value": 100.0
        },
        "meta": {},
        "id": "dfab93aa-7b3d-46a0-8d72-a62f6ae2cdf6",
        "severity": "critical"
      },
      "result": {
        "element_count": 10,
        "unexpected_count": 0,
        "unexpected_percent": 0.0,
        "partial_unexpected_list": [],
        "missing_count": 0,
        "missing_percent": 0.0,
        "unexpected_percent_total": 0.0,
        "unexpected_percent_nonmissing": 0.0,
        "partial_unexpected_counts": [],
        "partial_unexpected_index_list": []
      },
      "meta": {},
      "exception_info": {
        "raised_exception": false,
        "exception_traceback": null,
        "exception_message": null
      }
    },
    {
      "success": true,
      "expectation_config": {
        "type": "expect_column_distinct_values_to_be_in_set",
        "kwargs": {
          "batch_id": "customer_data_source-customer",
          "column": "status",
          "value_set": [
            "active",
            "inactive"
          ]
        },
        "meta": {},
        "id": "ae27598a-80b0-4062-a43c-aee3363fd43f",
        "severity": "critical"
      },
      "result": {
        "observed_value": null,
        "unexpected_count": 0,
        "partial_unexpected_list": []
      },
      "meta": {},
      "exception_info": {
        "raised_exception": false,
        "exception_traceback": null,
        "exception_message": null
      }
    },
    {
      "success": true,
      "expectation_config": {
        "type": "expect_column_values_to_not_be_null",
        "kwargs": {
          "batch_id": "customer_data_source-customer",
          "column": "email"
        },
        "meta": {},
        "id": "646bf99e-f1ca-4012-8491-eb4d507d9253",
        "severity": "critical"
      },
      "result": {
        "element_count": 10,
        "unexpected_count": 0,
        "unexpected_percent": 0.0,
        "partial_unexpected_list": [],
        "partial_unexpected_counts": [],
        "partial_unexpected_index_list": []
      },
      "meta": {},
      "exception_info": {
        "raised_exception": false,
        "exception_traceback": null,
        "exception_message": null
      }
    },
    {
      "success": false,
      "expectation_config": {
        "type": "expect_column_values_to_match_regex",
        "kwargs": {
          "batch_id": "customer_data_source-customer",
          "column": "email",
          "regex": "^[^@\\s]+@[^@\\s]+\\.[^@\\s]+$"
        },
        "meta": {},
        "id": "cc80d875-772e-4d1f-b209-f026c6a3b85f",
        "severity": "critical"
      },
      "result": {
        "element_count": 10,
        "unexpected_count": 1,
        "unexpected_percent": 10.0,
        "partial_unexpected_list": [
          "not-an-email"
        ],
        "missing_count": 0,
        "missing_percent": 0.0,
        "unexpected_percent_total": 10.0,
        "unexpected_percent_nonmissing": 10.0,
        "partial_unexpected_counts": [
          {
            "value": "not-an-email",
            "count": 1
          }
        ],
        "partial_unexpected_index_list": [
          3
        ]
      },
      "meta": {},
      "exception_info": {
        "raised_exception": false,
        "exception_traceback": null,
        "exception_message": null
      }
    }
  ],
  "suite_name": "customer_quality_suite_v1",
  "suite_parameters": {},
  "statistics": {
    "evaluated_expectations": 6,
    "successful_expectations": 5,
    "unsuccessful_expectations": 1,
    "success_percent": 83.33333333333334
  },
  "meta": {
    "great_expectations_version": "1.23.1",
    "batch_spec": {
      "batch_data": "PandasDataFrame"
    },
    "batch_markers": {
      "ge_load_time": "20260927T141339.212098Z",
      "pandas_data_fingerprint": "cd9e72c41b343a1d0bc763418f925aec"
    },
    "active_batch_definition": {
      "datasource_name": "customer_data_source",
      "data_connector_name": "fluent",
      "data_asset_name": "customer",
      "batch_identifiers": {
        "dataframe": "<DATAFRAME>"
      }
    }
  },
  "id": null
}

saving the suite

In [ ]:
print(context.suites.all())

[{
  "name": "customer_quality_suite_v1",
  "id": "f00466fd-f13f-4c73-9ffc-2e58136e66fd",
  "expectations": [
    {
      "type": "expect_column_values_to_not_be_null",
      "kwargs": {
        "column": "customer_id"
      },
      "meta": {},
      "id": "602d8e76-98a7-4b33-9c58-3b821e1ac62d",
      "severity": "critical"
    },
    {
      "type": "expect_column_values_to_be_unique",
      "kwargs": {
        "column": "customer_id"
      },
      "meta": {},
      "id": "cbf63011-d237-40f0-9607-614a456da495",
      "severity": "critical"
    },
    {
      "type": "expect_column_values_to_be_between",
      "kwargs": {
        "column": "age",
        "min_value": 18.0,
        "max_value": 100.0
      },
      "meta": {},
      "id": "dfab93aa-7b3d-46a0-8d72-a62f6ae2cdf6",
      "severity": "critical"
    },
    {
      "type": "expect_column_distinct_values_to_be_in_set",
      "kwargs": {
        "column": "status",
        "value_set": [
          "active",
          "inactive"
        ]
      },
      "meta": {},
      "id": "ae27598a-80b0-4062-a43c-aee3363fd43f",
      "severity": "critical"
    },
    {
      "type": "expect_column_values_to_not_be_null",
      "kwargs": {
        "column": "email"
      },
      "meta": {},
      "id": "646bf99e-f1ca-4012-8491-eb4d507d9253",
      "severity": "critical"
    },
    {
      "type": "expect_column_values_to_match_regex",
      "kwargs": {
        "column": "email",
        "regex": "^[^@\\s]+@[^@\\s]+\\.[^@\\s]+$"
      },
      "meta": {},
      "id": "cc80d875-772e-4d1f-b209-f026c6a3b85f",
      "severity": "critical"
    }
  ],
  "meta": {
    "great_expectations_version": "1.23.1"
  },
  "notes": null
}]

In [ ]:
print(context.data_sources.all())

{'customer_data_source': PandasDatasource(type='pandas', name='customer_data_source', id=UUID('248e7d78-3d01-473d-8dee-00075df507c6'), assets=[DataFrameAsset(name='customer', type='dataframe', id=UUID('f5da1dad-07f1-421b-b811-bd8ac68cb895'), order_by=[], batch_metadata={}, batch_definitions=[BatchDefinition(id=UUID('91601f81-3fa2-4c32-ba56-15b16e81b925'), name='customers_batch', partitioner=None)])])}

In [ ]:
print(context)

{
  "checkpoint_store_name": "checkpoint_store",
  "config_version": 4,
  "data_docs_sites": {
    "local_site": {
      "class_name": "SiteBuilder",
      "show_how_to_buttons": true,
      "store_backend": {
        "class_name": "TupleFilesystemStoreBackend",
        "base_directory": "C:\\Users\\Thiru\\AppData\\Local\\Temp\\tmp0ax_po9f"
      },
      "site_index_builder": {
        "class_name": "DefaultSiteIndexBuilder"
      }
    }
  },
  "expectations_store_name": "expectations_store",
  "fluent_datasources": {
    "customer_data_source": {
      "type": "pandas",
      "name": "customer_data_source",
      "id": "248e7d78-3d01-473d-8dee-00075df507c6",
      "assets": [
        {
          "name": "customer",
          "type": "dataframe",
          "id": "f5da1dad-07f1-421b-b811-bd8ac68cb895",
          "batch_metadata": {},
          "batch_definitions": [
            {
              "id": "91601f81-3fa2-4c32-ba56-15b16e81b925",
              "name": "customers_batch"
            }
          ]
        }
      ]
    }
  },
  "stores": {
    "expectations_store": {
      "class_name": "ExpectationsStore",
      "store_backend": {
        "class_name": "InMemoryStoreBackend"
      }
    },
    "validation_results_store": {
      "class_name": "ValidationResultsStore",
      "store_backend": {
        "class_name": "InMemoryStoreBackend"
      }
    },
    "checkpoint_store": {
      "class_name": "CheckpointStore",
      "store_backend": {
        "class_name": "InMemoryStoreBackend"
      }
    },
    "validation_definition_store": {
      "class_name": "ValidationDefinitionStore",
      "store_backend": {
        "class_name": "InMemoryStoreBackend"
      }
    }
  },
  "validation_results_store_name": "validation_results_store"
}

Data docs

In [ ]:
print([x for x in dir(context) if "doc" in x.lower()])

['__doc__', '_build_data_docs', '_clean_data_docs_site', '_init_site_builder_for_data_docs_site_creation', '_open_data_docs', 'add_data_docs_site', 'build_data_docs', 'clean_data_docs', 'delete_data_docs_site', 'get_docs_sites_urls', 'list_data_docs_sites', 'open_data_docs', 'update_data_docs_site']

In [ ]:
help(context.build_data_docs)

Help on method build_data_docs in module great_expectations.data_context.data_context.abstract_data_context:

build_data_docs(
    site_names: 'list[str] | None' = None,
    resource_identifiers: 'list[ExpectationSuiteIdentifier] | list[ValidationResultIdentifier] | None' = None,
    dry_run: 'bool' = False,
    build_index: 'bool' = True
) -> 'dict[str, str]' method of great_expectations.data_context.data_context.ephemeral_data_context.EphemeralDataContext instance
    --Public API--Build Data Docs for your project.

    --Documentation--
        - https://docs.greatexpectations.io/docs/terms/data_docs/

    Args:
        site_names: if specified, build data docs only for these sites, otherwise,
            build all the sites specified in the context's config
        resource_identifiers: a list of resource identifiers (ExpectationSuiteIdentifier,
            ValidationResultIdentifier). If specified, rebuild HTML
            (or other views the data docs sites are rendering) only for
            the resources in this list. This supports incremental build
            of data docs sites (e.g., when a new validation result is created)
            and avoids full rebuild.
        dry_run: a flag, if True, the method returns a structure containing the
            URLs of the sites that *would* be built, but it does not build
            these sites.
        build_index: a flag if False, skips building the index page

    Returns:
        A dictionary with the names of the updated data documentation sites as keys and the location info
        of their index.html files as values

    Raises:
        ClassInstantiationError: Site config in your Data Context config is not valid.

In [ ]:
data_docs = context.build_data_docs()
print(data_docs)

{'local_site': 'file://C:\\Users\\Thiru\\AppData\\Local\\Temp\\tmp0ax_po9f\\index.html'}

In [ ]:
print(data_docs["local_site"])

file://C:\Users\Thiru\AppData\Local\Temp\tmp0ax_po9f\index.html

In [ ]:
print(data_docs)

{'local_site': 'file://C:\\Users\\Thiru\\AppData\\Local\\Temp\\tmp0ax_po9f\\index.html'}

In [ ]:
print(type(context))

<class 'great_expectations.data_context.data_context.ephemeral_data_context.EphemeralDataContext'>

In [ ]:
[x for x in dir(context) if "project" in x.lower() or "context" in x.lower()]

['_construct_data_context_id',
 '_data_context_id',
 '_init_project_config',
 '_project_config',
 '_save_project_config',
 'convert_to_file_context',
 'data_context_id',
 'get_or_create_data_context_config',
 'project_config_with_variables_substituted',
 'update_project_config']

In [ ]:
help(gx.get_context)

Help on function get_context in module great_expectations.data_context.data_context.context_factory:

get_context(
    project_config: 'DataContextConfig | Mapping | None' = None,
    context_root_dir: 'PathStr | None' = None,
    project_root_dir: 'PathStr | None' = None,
    runtime_environment: 'dict | None' = None,
    cloud_base_url: 'str | None' = None,
    cloud_access_token: 'str | None' = None,
    cloud_organization_id: 'str | None' = None,
    cloud_workspace_id: 'str | None' = None,
    cloud_mode: 'bool | None' = None,
    user_agent_str: 'str | None' = None,
    mode: 'ContextModes | None' = None
) -> 'AbstractDataContext'
    --Public API--Method to return the appropriate Data Context depending on parameters and environment.

    Usage:
        `import great_expectations as gx`

        `my_context = gx.get_context(<insert_your_parameters>)`

    This method returns the appropriate Data Context based on which parameters you've passed and / or your environment configuration:

    - FileDataContext: Configuration stored in a file.
    - EphemeralDataContext: Configuration passed in at runtime.
    - CloudDataContext: Configuration stored in Great Expectations Cloud.

    Read on for more details about each of the Data Context types:

    **FileDataContext:** A Data Context configured via a yaml file. Returned by default if you have no cloud configuration set up and pass no parameters. If you pass context_root_dir, we will look for a great_expectations.yml configuration there. If not we will look at the following locations:

    - Path defined in a GX_HOME environment variable.
    - The current directory.
    - Parent directories of the current directory.

    Relevant parameters

    - project_root_dir: Provide the project root where a GX project exists or will be scaffolded (contains the context root).
    - context_root_dir: Provide an alternative directory to look for GX config.
    - project_config: Optionally override the configuration on disk - only if `context_root_dir` is also provided.
    - runtime_environment: Optionally override specific configuration values.

    **EphemeralDataContext:** A temporary, in-memory Data Context typically used in a pipeline. The default if you pass in only a project_config and have no cloud configuration set up.

    Relevant parameters

    - project_config: Used to configure the Data Context.
    - runtime_environment: Optionally override specific configuration values.

    **CloudDataContext (shut down):** GX Cloud has been shut down. Requesting a cloud-backed context no longer returns a `CloudDataContext` -- it raises a `GreatExpectationsError` immediately. A request resolves to the (removed) cloud branch when `mode="cloud"` or `cloud_mode=True` is passed, when a complete set of ``cloud_*`` parameters is supplied, or when ``GX_CLOUD_*`` environment variables / a great_expectations.conf file provide a complete cloud configuration. The `CloudDataContext` class and the ``cloud_*`` parameters remain importable for source compatibility through the v1 line and are removed in great_expectations 2.0.

    Args:
        project_config: In-memory configuration for Data Context.
        context_root_dir (str or pathlib.Path): Path to directory that contains great_expectations.yml file
        project_root_dir (str or pathlib.Path): Path to project root (contains context root with GX config)
        runtime_environment: A dictionary of values can be passed to a DataContext when it is instantiated.
            These values will override both values from the config variables file and
            from environment variables.
        cloud_base_url: url for GX Cloud endpoint.
        cloud_access_token: access_token for GX Cloud account.
        cloud_organization_id: org_id for GX Cloud account.
        cloud_mode: whether GX resolves to the (shut-down) Cloud branch when ``mode``
            is not specified (default None). If None, the cloud branch is resolved when
            a complete cloud configuration is discoverable; set to False to opt out of
            that auto-detection. GX Cloud is shut down, so a cloud-resolving call raises
            rather than building a context.
        user_agent_str: Optional string, should be of format <PRODUCT> / <VERSION> <COMMENT>
        mode: which mode to use. One of: ephemeral, file, cloud. ``mode="cloud"`` always
            resolves to the (shut-down) cloud branch and raises, regardless of
            ``cloud_mode``; ``mode="ephemeral"`` and ``mode="file"`` always build that
            context type, even when ``GX_CLOUD_*`` configuration is present.

    Returns:
        A Data Context. Either a FileDataContext or an EphemeralDataContext
        depending on environment and/or parameters.

        Note: GX Cloud has been shut down. Requesting a cloud-backed context
        (``mode="cloud"``, ``cloud_mode=True``, a complete set of ``cloud_*``
        parameters, or ``GX_CLOUD_*`` configuration) no longer returns a
        CloudDataContext; it raises immediately. The cloud branch is removed in
        great_expectations 2.0.

    Raises:
        GreatExpectationsError: A cloud-backed context was requested. GX Cloud is
            shut down, so this raises instead of building a context.

In [ ]:
print(type(context))

<class 'great_expectations.data_context.data_context.ephemeral_data_context.EphemeralDataContext'>

In [ ]:
from pathlib import Path

print(Path.cwd())

d:\Study\Data Engineering\great_learning\great-expectations-learning\projects\01-customer-data-quality

In [1]:
import great_expectations as gx

context = gx.get_context(
    project_root_dir="."
)

print(type(context))

<class 'great_expectations.data_context.data_context.file_data_context.FileDataContext'>

In [2]:
from pathlib import Path

for path in Path(".").iterdir():
    print(path)

data
gx
inspect_data.ipynb
README.md

In [3]:
print(context.root_directory)

d:\Study\Data Engineering\great_learning\great-expectations-learning\projects\01-customer-data-quality\gx

In [4]:
from pathlib import Path

gx_dir = Path("gx")

for path in gx_dir.rglob("*"):
    print(path)

gx\.gitignore
gx\checkpoints
gx\expectations
gx\great_expectations.yml
gx\plugins
gx\uncommitted
gx\validation_definitions
gx\expectations\.ge_store_backend_id
gx\expectations\customer_quality_suite_v1.json
gx\plugins\custom_data_docs
gx\uncommitted\config_variables.yml
gx\uncommitted\data_docs
gx\uncommitted\validations
gx\uncommitted\validations\.ge_store_backend_id
gx\plugins\custom_data_docs\renderers
gx\plugins\custom_data_docs\styles
gx\plugins\custom_data_docs\views
gx\plugins\custom_data_docs\styles\data_docs_custom_styles.css

In [5]:
from pathlib import Path

config_file = Path("gx/great_expectations.yml")

print(config_file.read_text())

# Welcome to Great Expectations! Always know what to expect from your data.
#
# Here you can define datasources, batch kwargs generators, integrations and
# more. This file is intended to be committed to your repo. For help with
# configuration please:
#   - Read our docs: https://docs.greatexpectations.io/docs/guides/connecting_to_your_data/connect_to_data_overview/#2-configure-your-datasource
#   - Join our slack channel: http://greatexpectations.io/slack

# config_version refers to the syntactic version of this config file, and is used in maintaining backwards compatibility
# It is auto-generated and usually does not need to be changed.
config_version: 4.0

# This config file supports variable substitution which enables: 1) keeping
# secrets out of source control & 2) environment-based configuration changes
# such as staging vs prod.
#
# When GX encounters substitution syntax (like `my_key: ${my_value}` or
# `my_key: $my_value`) in the great_expectations.yml file, it will attempt
# to replace the value of `my_key` with the value from an environment
# variable `my_value` or a corresponding key read from this config file,
# which is defined through the `config_variables_file_path`.
# Environment variables take precedence over variables defined here.
#
# Substitution values defined here can be a simple (non-nested) value,
# nested value such as a dictionary, or an environment variable (i.e. ${ENV_VAR})
#
#
# https://docs.greatexpectations.io/docs/guides/setup/configuring_data_contexts/how_to_configure_credentials


config_variables_file_path: uncommitted/config_variables.yml

# The plugins_directory will be added to your python path for custom modules
# used to override and extend Great Expectations.
plugins_directory: plugins/

stores:
# Stores are configurable places to store things like Expectations, Validations
# Data Docs, and more. These are for advanced users only - most users can simply
# leave this section alone.
  expectations_store:
    class_name: ExpectationsStore
    store_backend:
      class_name: TupleFilesystemStoreBackend
      base_directory: expectations/

  validation_results_store:
    class_name: ValidationResultsStore
    store_backend:
      class_name: TupleFilesystemStoreBackend
      base_directory: uncommitted/validations/

  checkpoint_store:
    class_name: CheckpointStore
    store_backend:
      class_name: TupleFilesystemStoreBackend
      suppress_store_backend_id: true
      base_directory: checkpoints/

  validation_definition_store:
    class_name: ValidationDefinitionStore
    store_backend:
      class_name: TupleFilesystemStoreBackend
      base_directory: validation_definitions/

expectations_store_name: expectations_store
validation_results_store_name: validation_results_store
checkpoint_store_name: checkpoint_store

data_docs_sites:
  # Data Docs make it simple to visualize data quality in your project. These
  # include Expectations, Validations & Profiles. The are built for all
  # Datasources from JSON artifacts in the local repo including validations &
  # profiles from the uncommitted directory. Read more at https://docs.greatexpectations.io/docs/terms/data_docs
  local_site:
    class_name: SiteBuilder
    show_how_to_buttons: true
    store_backend:
      class_name: TupleFilesystemStoreBackend
      base_directory: uncommitted/data_docs/local_site/
    site_index_builder:
      class_name: DefaultSiteIndexBuilder
fluent_datasources:
  customer_data_source:
    type: pandas
    id: 7059582c-3bbc-49e3-9147-52d997a0ddc0
    assets:
      customer:
        type: dataframe
        id: fcae5632-0af7-43f8-9346-e887c8c64069
        batch_metadata: {}
        batch_definitions:
          customers_batch:
            id: 2bb5286c-2727-4a2d-99e6-6d7bb0c8ef7c
            partitioner:
analytics_enabled:
data_context_id: a942e095-dfc7-4405-ab01-c8f97d456320

In [6]:
print(context.suites.all())

[{
  "name": "customer_quality_suite_v1",
  "id": "7345e587-1a34-4690-a9d1-9bd953fdb693",
  "expectations": [
    {
      "type": "expect_column_values_to_not_be_null",
      "kwargs": {
        "column": "customer_id"
      },
      "meta": {},
      "id": "484b768d-65ab-49fd-b8a7-e60a6b750825",
      "severity": "critical"
    }
  ],
  "meta": {
    "great_expectations_version": "1.23.1"
  },
  "notes": null
}]

In [7]:
print(context.suites)

<great_expectations.core.factory.suite_factory.SuiteFactory object at 0x000002698D9C6CF0>

In [19]:
[x for x in dir(context) if "del" in dir(context.suites)]

[]

In [8]:
context.suites.all()

[{
   "name": "customer_quality_suite_v1",
   "id": "7345e587-1a34-4690-a9d1-9bd953fdb693",
   "expectations": [
     {
       "type": "expect_column_values_to_not_be_null",
       "kwargs": {
         "column": "customer_id"
       },
       "meta": {},
       "id": "484b768d-65ab-49fd-b8a7-e60a6b750825",
       "severity": "critical"
     }
   ],
   "meta": {
     "great_expectations_version": "1.23.1"
   },
   "notes": null
 }]

In [10]:
suite = context.suites.add(
    gx.ExpectationSuite(
        name="customer_quality_suite_v2"
    )
)

In [11]:
print(context.suites.all())

[{
  "name": "customer_quality_suite_v1",
  "id": "7345e587-1a34-4690-a9d1-9bd953fdb693",
  "expectations": [
    {
      "type": "expect_column_values_to_not_be_null",
      "kwargs": {
        "column": "customer_id"
      },
      "meta": {},
      "id": "484b768d-65ab-49fd-b8a7-e60a6b750825",
      "severity": "critical"
    }
  ],
  "meta": {
    "great_expectations_version": "1.23.1"
  },
  "notes": null
}, {
  "name": "customer_quality_suite_v2",
  "id": "58206d32-bf95-472d-bad7-20718c6ea9ba",
  "expectations": [],
  "meta": {
    "great_expectations_version": "1.23.1"
  },
  "notes": null
}]

In [20]:
dir(suite)

['Config',
 '__abstractmethods__',
 '__annotations__',
 '__class__',
 '__class_vars__',
 '__config__',
 '__copy__',
 '__custom_root_type__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__exclude_fields__',
 '__fields__',
 '__fields_set__',
 '__firstlineno__',
 '__format__',
 '__ge__',
 '__get_validators__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__include_fields__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__json_encoder__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__post_root_validators__',
 '__pre_root_validators__',
 '__pretty__',
 '__private_attributes__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__repr_args__',
 '__repr_name__',
 '__repr_str__',
 '__rich_repr__',
 '__schema_cache__',
 '__setattr__',
 '__setstate__',
 '__signature__',
 '__sizeof__',
 '__slots__',
 '__static_attributes__',
 '__str__',
 '__subclasshook__',
 '__try_update_forward_refs__',
 '__validators__',
 '_abc_impl',
 '_add_array_params',
 '_add_mostly_pct_param',
 '_atomic_diagnostic_observed_value',
 '_build_evr',
 '_calculate_keys',
 '_copy_and_set_values',
 '_decompose_class',
 '_descriptive_column_properties_table_missing_count_row_renderer',
 '_descriptive_column_properties_table_missing_percent_row_renderer',
 '_diagnostic_failed',
 '_diagnostic_meta_properties_renderer',
 '_diagnostic_observed_value_renderer',
 '_diagnostic_status_icon_renderer',
 '_diagnostic_unexpected_statement_renderer',
 '_diagnostic_unexpected_table_renderer',
 '_enforce_dict_if_root',
 '_get_array_string',
 '_get_default_value',
 '_get_domain_kwargs',
 '_get_observed_value_from_evr',
 '_get_result_format',
 '_get_runtime_kwargs',
 '_get_strict_max_string',
 '_get_strict_min_string',
 '_get_success_kwarg',
 '_get_success_kwargs',
 '_get_value',
 '_include_rendered_content',
 '_init_private_attributes',
 '_iter',
 '_library_metadata',
 '_prescriptive_failed',
 '_prescriptive_renderer',
 '_prescriptive_summary',
 '_prescriptive_template',
 '_register_renderer_functions',
 '_save_callback',
 '_to_normalized_self_dict',
 '_transform_legacy_row_condition',
 '_validate',
 '_validate_metric_value_between',
 '_validate_result_format',
 '_validate_row_condition',
 '_warn_if_result_format_config_in_expectation_configuration',
 '_warn_if_result_format_config_in_runtime_configuration',
 'args_keys',
 'batch_id',
 'catch_exceptions',
 'column',
 'condition_parser',
 'configuration',
 'construct',
 'copy',
 'description',
 'dict',
 'domain_keys',
 'domain_type',
 'examples',
 'expectation_type',
 'from_orm',
 'get_allowed_config_keys',
 'get_validation_dependencies',
 'id',
 'is_abstract',
 'json',
 'library_metadata',
 'map_metric',
 'meta',
 'metric_dependencies',
 'metrics_validate',
 'mostly',
 'notes',
 'parse_file',
 'parse_obj',
 'parse_raw',
 'print_diagnostic_checklist',
 'register_save_callback',
 'render',
 'rendered_content',
 'result_format',
 'row_condition',
 'run_diagnostics',
 'runtime_keys',
 'save',
 'schema',
 'schema_json',
 'severity',
 'success_keys',
 'suite_parameter_options',
 'update_forward_refs',
 'validate',
 'validate_',
 'validate_configuration',
 'version',
 'windows']

In [12]:
expectation = gx.expectations.ExpectColumnValuesToNotBeNull(
    column="customer_id"
)

suite = suite.add_expectation(expectation)

In [ ]:
print(suite.expectations)

AttributeError: 'ExpectColumnValuesToNotBeNull' object has no attribute 'expectations'

In [ ]:
context.suites.all()

[{
   "name": "customer_quality_suite_v1",
   "id": "7345e587-1a34-4690-a9d1-9bd953fdb693",
   "expectations": [
     {
       "type": "expect_column_values_to_not_be_null",
       "kwargs": {
         "column": "customer_id"
       },
       "meta": {},
       "id": "484b768d-65ab-49fd-b8a7-e60a6b750825",
       "severity": "critical"
     }
   ],
   "meta": {
     "great_expectations_version": "1.23.1"
   },
   "notes": null
 }]

In [ ]:
context.suites.get("customer_quality_suite_v1")

{
  "name": "customer_quality_suite_v1",
  "id": "7345e587-1a34-4690-a9d1-9bd953fdb693",
  "expectations": [
    {
      "type": "expect_column_values_to_not_be_null",
      "kwargs": {
        "column": "customer_id"
      },
      "meta": {},
      "id": "484b768d-65ab-49fd-b8a7-e60a6b750825",
      "severity": "critical"
    }
  ],
  "meta": {
    "great_expectations_version": "1.23.1"
  },
  "notes": null
}

In [ ]:
suite.expectations

AttributeError: 'ExpectColumnValuesToNotBeNull' object has no attribute 'expectations'

In [ ]:
#customer id should be unique 

expectation = gx.expectations.ExpectColumnValuesToBeUnique(
    column="customer_id"
)

In [ ]:
suite.add_expectation(expectation)

AttributeError: 'ExpectColumnValuesToNotBeNull' object has no attribute 'add_expectation'